addon/components/destructive-button.js

Use TargetActionSupport

---

addon/components/app-header.js
app/templates/components/app-header.hbs

Handle custom logo

---

bower.json
tests/dummy/app/templates/buttons.hbs
tests/dummy/app/templates/partials/buttons/icons.hbs
tests/dummy/app/templates/partials/typography-fonts.hbs

OSS documentation updates

---

app/templates/components/upf-table/pagination.hbs
bower.json

Add link disable for not previous/next page

---

addon/components/upf-table/index.js
app/templates/components/upf-table.hbs

Setup the value on the searchSquery only when the page is loaded.

Avoid the change twice

---

addon/components/upf-table/pagination.js
app/templates/components/upf-table.hbs
app/templates/components/upf-table/pagination.hbs

WIP
Requires PR#140  https://github.com/upfluence/publishr-admin-web/pull/140

White action buttons for tables

---

.github/workflows/ci.yml

Adds caching support to the Yarn install step in the CI

CI : Add caching for yarn

---

.storybook/preview.js
stories/Guidelines.stories.mdx

Adds a Developer Guidelines section to the Storybook with a section for tooling
Related https://github.com/upfluence/backlog/issues/421

Add Developer Guidelines to doc

---

addon/modifiers/enable-popover.js
app/modifiers/enable-popover.js
package.json

modifiers/enable-popover: Add popover modifer

---

.storybook/main.js
.storybook/preview.js
addon/modifiers/Modifiers.stories.mdx
addon/modifiers/on-click-outside.js
app/modifiers/on-click-outside.js

Adds a modifier allowing to trigger a function when we click outside the element it's applied on.

Add on-click-outside modifier + doc

---

app/modifiers/on-click-outside.js

Fix wrong import path for modifier.

fix modifier import path

---

.github/pull_request_template.md
addon/modifiers/Modifiers.stories.mdx
addon/modifiers/enable-tooltip.js
app/modifiers/enable-tooltip.js

Add new tooltip modifier
Related to: https://github.com/upfluence/backlog/issues/616

Add tooltip modifier

---

package.json

Drops the ember-cli-toggle package now that we have our own `ToggleSwitch` component.
Makes `oss-components` deprecation warning free 🥳 🎉

Drop ember-cli-toggle

---

app/styles/oss-components.less
index.js
package.json

Migrate to Font Awesome 5
Icon name changes => https://fontawesome.com/v5.15/how-to-use/on-the-web/setup/upgrading-from-version-4#name-changes

Migrate to Font Awesome 5

---

.storybook/styles/preview.less
.storybook/styles/stories/flex.less

Add flexbox documentation
Related to: (nothing)
Result here: https://github.com/upfluence/oss/pull/113

Add flexbox documentation

---

addon/utils/upf-local-storage.ts
app/utils/upf-local-storage.js
tests/unit/utils/upf-local-storage-test.js

Adds UPFLocalStorage utility class along with Unit Test.

Added: new UPFLocalStorage Utility along with unit tests

---

app/styles/input-container.less

Fixes the bad outline on yielded input focus

Fixes the bad outline on yielded input focus

---

addon/components/radio-button.js

Added: ability to keep a fixed width

Added: ability to keep a fixed width

---

addon/components/o-s-s/button.stories.js
stories/TBW.stories.js

Update OSS::Button doc. Add icon args

Update OSS::Button doc

---

addon/components/o-s-s/infinite-select.hbs
addon/components/o-s-s/infinite-select.ts
tests/integration/components/o-s-s/infinite-select-test.js
translations/en-us.yaml
yarn.lock

Add inline arg to disable floating menu and translation
Related to: https://github.com/upfluence/backlog/issues/1107

Add inline args to disable floating menu and translation

---

addon/components/o-s-s/infinite-select.stories.js
addon/components/o-s-s/power-select.hbs
addon/components/o-s-s/power-select.ts
addon/components/upf-checkbox.js
app/components/o-s-s/power-select.js
app/styles/oss-components.less
app/styles/power-select.less
tests/integration/components/o-s-s/power-select-test.ts
yarn.lock

Add an `OSS::PowerSelect` and tests
Add documentation for new `inline` arg of `OSS::InfiniteSelect`
Add `preventDefault` for `UpfCheckbox`
Related to: https://github.com/upfluence/backlog/issues/1107
New component

Add OSS::PowerSelect

---

addon/components/o-s-s/infinite-select.ts
addon/components/o-s-s/power-select.hbs
addon/modifiers/on-bottom-reached.ts
tests/integration/components/o-s-s/infinite-select-test.js
tests/integration/components/o-s-s/power-select-test.ts

Fix flaky tests of power-select
Related to: https://github.com/upfluence/backlog/issues/1107

Fix tests on OSS:PowerSelect

---

app/styles/input-container.less

Setup disabled style for inputs

input-container: extend input's disabled style

---

addon/components/o-s-s/infinite-select.stories.js
addon/components/o-s-s/power-select.stories.js
stories/TBW.stories.js

Update documentation for OSS:InfiniteSelect and OSS::PowerSelect
Related to: https://github.com/upfluence/backlog/issues/1105

Update documentation for OSS:InfiniteSelect and OSS::PowerSelect

---

addon/components/o-s-s/button.stories.js
addon/components/o-s-s/button.ts
app/styles/button.less
app/styles/oss-components.less
tests/dummy/app/templates/application.hbs
tests/integration/components/o-s-s/button-test.js
yarn.lock

Updated: OSS::Button to handle square buttons, more sizes & more skins

Updated: OSS::Button to handle square buttons, more sizes & more skins

---

addon/components/o-s-s/password-input.ts

Added: ability to disable regex validation on password-input component

Added: ability to disable regex validation on password-input component

---

index.js

Use font awesome pro when present.

use font awesome pro's fonts if present in the parent's deps

---

.github/workflows/ci.yml
.npmrc
addon/components/o-s-s/modal.js
package.json
yarn.lock

Add `isTesting` for OSS::Modal to fix tests
Add font awesome pro
Related to: nothing

Add isTesting for modals

---

.github/workflows/ci.yml

Move FONTAWESOME_NPM_AUTH_TOKEN to the right place
Related to: nothing

Move FONTAWESOME_NPM_AUTH_TOKEN to the right place

---

addon/components/o-s-s/badge.hbs
addon/components/o-s-s/badge.stories.js
addon/components/o-s-s/badge.ts
app/components/o-s-s/badge.js
app/styles/oss-components.less
index.js
tests/dummy/app/templates/application.hbs
tests/integration/components/o-s-s/badge-test.ts
translations/en-us.yaml

New component for using Badges.

basics for OSS::Badge component

---

addon/components/o-s-s/password-input.ts
tests/integration/components/o-s-s/password-input-test.ts

Ability to get the current state of the validation of the password input by passing a validates method.

Added: PasswordInput - returns the state of the validation

---

.storybook/preview-head.html
addon/components/o-s-s/star-rating.hbs
addon/components/o-s-s/star-rating.stories.js
addon/components/o-s-s/star-rating.ts
app/components/o-s-s/star-rating.js
app/styles/oss-components.less
app/styles/star-rating.less
tests/dummy/app/templates/application.hbs
tests/integration/components/o-s-s/star-rating-test.ts

A configurable component to display a star rating.

Added: OSS::StarRating component + tests + doc

---

addon/components/o-s-s/badge.hbs
addon/components/o-s-s/checkbox.hbs
addon/components/o-s-s/checkbox.stories.js
addon/components/o-s-s/checkbox.ts
addon/modifiers/on-bottom-reached.ts
app/components/o-s-s/checkbox.js
stories/TBW.stories.js
tests/integration/components/o-s-s/checkbox-test.ts

Add a new OSS::Checkbox component aiming to removing the existing `upf-checkbox`.

Add OSS::Checkbox component

---

addon/components/o-s-s/password-input.hbs
addon/components/o-s-s/password-input.stories.js
addon/components/o-s-s/password-input.ts
tests/integration/components/o-s-s/password-input-test.ts

Add placeholder for input password
Related to: https://github.com/upfluence/backlog/issues/1253

Add placeholder for input password

---

addon/components/o-s-s/button.stories.js
addon/components/o-s-s/button.ts
tests/dummy/app/templates/application.hbs
tests/integration/components/o-s-s/button-test.js
yarn.lock

Add tertiary button style
Related to: https://github.com/upfluence/backlog/issues/1237

Add tertiary button style

---

addon/utils/country-codes.ts

Related to: #[1338](https://github.com/upfluence/backlog/issues/1338)
Adds Provinces to the Country disctionnary

Adds Provinces to the Country disctionnary

---

addon/components/o-s-s/button.ts
addon/components/o-s-s/code-block.hbs
addon/components/o-s-s/code-block.stories.js
addon/components/o-s-s/code-block.ts
app/components/o-s-s/code-block.js
app/styles/code-block.less
app/styles/oss-components.less
tests/dummy/app/controllers/application.js
tests/dummy/app/templates/application.hbs
tests/integration/components/o-s-s/button-test.ts
tests/integration/components/o-s-s/code-block-test.ts
tests/integration/components/o-s-s/input-container-test.js
translations/en-us.yaml

The new component displays a codeblock.
See storybook documentation for more info.

Add OSS::CodeBlock Component

---

.storybook/preview-head.html
addon/components/o-s-s/modal-dialog.hbs
addon/components/o-s-s/modal-dialog.stories.js
addon/components/o-s-s/modal-dialog.ts
app/components/o-s-s/modal-dialog.js
app/styles/modal-dialog.less
app/styles/oss-components.less
tests/dummy/app/controllers/application.js
tests/dummy/app/templates/application.hbs
tests/integration/components/o-s-s/modal-dialog-test.ts
yarn.lock

Related to: #[1638](https://github.com/upfluence/backlog/issues/1638)

Add ModalDialog component + tests

---

addon/components/o-s-s/email-input.hbs
addon/components/o-s-s/email-input.stories.js
addon/components/o-s-s/email-input.ts
addon/components/o-s-s/password-input.ts
app/components/o-s-s/email-input.js
tests/integration/components/o-s-s/email-input-test.ts
translations/en-us.yaml

Adds a component for typing emails with built-in validation.

Add support for email input component

---

addon/components/o-s-s/modal-dialog.stories.js
addon/components/o-s-s/modal-dialog.ts
tests/integration/components/o-s-s/modal-dialog-test.ts

Fixed: ModalDialogs are now appended to body

Fixed: ModalDialogs are now appended to body

---

.github/workflows/ci.yml
tests/integration/components/o-s-s/code-block-test.ts
tests/integration/components/o-s-s/phone-number-input-test.ts

Fixed: failing tests

---

addon/components/column-visibility-panel.js
addon/components/o-s-s/infinite-select.ts
addon/components/o-s-s/modal-dialog.ts
addon/components/o-s-s/modal.js
addon/modifiers/on-bottom-reached.ts
addon/modifiers/on-click-outside.js
addon/services/toast.ts
tests/integration/components/o-s-s/infinite-select-test.js

Added: Run all event listeners in ember runloop

Trying to fix flaky tests on CI

---

addon/components/o-s-s/banner.hbs
app/styles/banner.less
tests/integration/components/o-s-s/banner-test.ts

OSS::Banner updated with new styling
Related to: #[1721](https://github.com/upfluence/backlog/issues/1721)

OSS::Banner updated with new styling

---

addon/components/o-s-s/badge.ts
addon/components/o-s-s/button.ts
addon/components/o-s-s/checkbox.ts
addon/components/o-s-s/country-selector.ts
addon/components/o-s-s/currency-input.ts
addon/components/o-s-s/email-input.ts
addon/components/o-s-s/link.ts
addon/components/o-s-s/modal-dialog.ts
addon/components/o-s-s/modal.stories.js
addon/components/o-s-s/password-input.ts
addon/components/o-s-s/phone-number-input.ts
addon/components/o-s-s/power-select.ts
addon/components/o-s-s/star-rating.ts
addon/components/o-s-s/tag.ts
addon/components/o-s-s/toggle-switch.js
addon/utils/upf-local-storage.ts
tests/integration/components/o-s-s/badge-test.ts
tests/integration/components/o-s-s/button-test.ts
tests/integration/components/o-s-s/checkbox-test.ts
tests/integration/components/o-s-s/country-selector-test.ts
tests/integration/components/o-s-s/currency-input-test.ts
tests/integration/components/o-s-s/email-input-test.ts
tests/integration/components/o-s-s/link-test.ts
tests/integration/components/o-s-s/modal-dialog-test.ts
tests/integration/components/o-s-s/password-input-test.ts
tests/integration/components/o-s-s/phone-number-input-test.ts
tests/integration/components/o-s-s/power-select-test.ts
tests/integration/components/o-s-s/star-rating-test.ts
tests/integration/components/o-s-s/tag-test.ts
tests/integration/components/o-s-s/toggle-switch-test.js

Use assert to check for mandatory args

Use assert to check for mandatory args

---

addon/components/o-s-s/array-input.hbs
addon/components/o-s-s/chip.hbs
addon/components/o-s-s/chip.ts
addon/components/o-s-s/power-select.hbs
addon/components/o-s-s/power-select.ts
app/components/o-s-s/multi-select.js
app/styles/atoms/chip.less
app/styles/power-select.less
tests/dummy/app/templates/application.hbs
tests/integration/components/o-s-s/power-select-test.ts

- Use PowerSelect as dropdown instead of sticky infinite select
- Updated the Chip to remove its margins as it's not its responsibility to set it 
- Update the ArrayInput component to add said margins

Power select as dropdown

---

app/styles/core-v2/_variables.less

css-var based utility classes for border colors

css-var based utility classes for border colors

---

addon/components/o-s-s/button-dropdown.hbs
addon/components/o-s-s/button-dropdown.stories.js
addon/components/o-s-s/button-dropdown.ts
addon/components/o-s-s/currency-input.hbs
app/components/o-s-s/button-dropdown.js
app/styles/molecules/button-dropdown.less
app/styles/oss-components.less
tests/integration/components/o-s-s/button-dropdown-test.ts

Add support for button dropdown component

Add support for button dropdown component

---

addon/components/o-s-s/avatar.hbs
addon/components/o-s-s/avatar.stories.js
addon/components/o-s-s/avatar.ts
app/components/o-s-s/avatar.js
app/styles/atoms/avatar.less
app/styles/oss-components.less
tests/dummy/app/templates/application.hbs
tests/integration/components/o-s-s/avatar-test.ts

Add new component OSS::Avatar which will be able to display an image or initials
Related to:[ #1800](https://github.com/upfluence/backlog/issues/1800)

New component OSS::Avatar

---

app/styles/atoms/avatar.less

Delete border around OSS::Avatar
Related to:[ #1800](https://github.com/upfluence/backlog/issues/1800)

Update after OSS::Avatar QA

---

addon/components/o-s-s/upload-area.hbs
addon/components/o-s-s/upload-area.ts
app/styles/molecules/upload-area.less

Upload area animations for hover and drag
Related to: https://github.com/upfluence/backlog/issues/2004

Upload area animations for hover and drag

---

addon/components/o-s-s/upload-area.hbs
addon/components/o-s-s/upload-area.ts

Move logic to template for image fingerprint for upload area
Related to: https://github.com/upfluence/backlog/issues/2004
Display image in prod

Move logic to template for image fingerprint for upload area

---

addon/components/o-s-s/toggle-switch.hbs

Add attributes to toggle-switch hbs
Related to: https://github.com/upfluence/backlog/issues/1948

Add attributes to toggle-switch hbs

---

addon/components/o-s-s/radio-button.hbs
addon/components/o-s-s/radio-button.stories.js
addon/components/o-s-s/radio-button.ts
app/components/o-s-s/radio-button.js
app/styles/atoms/radio-button.less
app/styles/oss-components.less
testem.js
tests/dummy/app/controllers/application.js
tests/dummy/app/templates/application.hbs
tests/integration/components/o-s-s/radio-button-test.ts

Adds a new version of the radiobuttons in the OSS section.

OSS::RadioButton with documetation & tests 

---

app/styles/modal-dialog.less

Added: encapsulation around calc for modal dialog

Added: encapsulation around calc for modal dialog

---

app/styles/modal-dialog.less

Fixes broken layout of ModalDialog, see screenshots.
Related to: #[2050](https://github.com/upfluence/backlog/issues/2050)
Screenshots before fix :
Screenshots after fix:

Added: max-width on modal-dialog to prevent bugs

---

addon/components/o-s-s/upload-area.hbs
addon/components/o-s-s/upload-item.hbs
app/styles/mixins/_typography.less
tests/dummy/app/templates/application.hbs

Add ellipsis on file-uploader filename.
Related to: #[2052](https://github.com/upfluence/backlog/issues/2052)

Add ellipsis on file-uploader filename

---

addon/components/o-s-s/banner.hbs
addon/components/o-s-s/banner.stories.js
app/styles/banner.less
tests/dummy/app/templates/application.hbs
tests/integration/components/o-s-s/banner-test.ts

Update OSS::Banner with selected argument
Add missing tests
Update doc
Related to: https://github.com/upfluence/backlog/issues/2028

Update OSS::Banner with selected argument

---

app/styles/banner.less

Add transition for banner selected
Related to: https://github.com/upfluence/backlog/issues/2028

Add transition for banner selected

---

addon/components/o-s-s/url-input.hbs
addon/components/o-s-s/url-input.stories.js
addon/components/o-s-s/url-input.ts
app/components/o-s-s/url-input.js
tests/dummy/app/controllers/application.js
tests/dummy/app/templates/application.hbs
tests/integration/components/o-s-s/url-input-test.ts
translations/en-us.yaml

Adds OSS::UrlInput component + tests & documentation
Related to: #https://github.com/upfluence/backlog/issues/2016

Adds OSS::UrlInput component + tests & documentation

---

addon/components/o-s-s/url-input.hbs

Adds "...attributes" to OSS::UrlInput
Related to: #https://github.com/upfluence/backlog/issues/2016

Adds "...attributes" to OSS::UrlInput

---

addon/components/o-s-s/copy.hbs
addon/components/o-s-s/copy.stories.js
addon/components/o-s-s/copy.ts
addon/modifiers/enable-tooltip.js
app/components/o-s-s/copy.js
app/styles/atoms/copy.less
app/styles/oss-components.less
tests/dummy/app/templates/application.hbs
tests/integration/components/o-s-s/code-block-test.ts
tests/integration/components/o-s-s/copy-test.ts
translations/en-us.yaml

Add OSS::Copy component (based with copy component in publishr-admin-web)
Related to: https://github.com/upfluence/backlog/issues/2069

Add OSS::Copy component

---

addon/modifiers/enable-tooltip.js

Fix tooltip modifier
Related to: nothing

Fix tooltip modifier

---

addon/components/o-s-s/copy.hbs
addon/components/o-s-s/copy.ts
app/styles/atoms/copy.less
app/styles/oss-components.less
tests/integration/components/o-s-s/copy-test.ts
translations/en-us.yaml

Final version for copy component
Related to: https://github.com/upfluence/backlog/issues/2069

Final version for copy component

---

addon/components/o-s-s/toggle-switch.js
addon/components/o-s-s/toggle-switch.stories.js

Fixed: disable status of the toggle switch

Fixed: disable status of the toggle switch

---

app/styles/atoms/avatar.less

Add min-width & min-height for OSS::Avatar
Related to: https://github.com/upfluence/backlog/issues/2164
Avoid to deform avatar in flex box

Add min-width & min-height for OSS::Avatar

---

addon/components/o-s-s/upload-area.hbs
addon/components/o-s-s/upload-area.ts
tests/integration/components/o-s-s/upload-area-test.ts

Adds support for uploading multiple files

Add support for multiple upload

---

addon-test-support/custom-assertions/tooltip.ts
addon-test-support/register-assertions.ts
addon/modifiers/Modifiers.stories.mdx
addon/modifiers/enable-tooltip.stories.js
addon/modifiers/enable-tooltip.ts
tests/integration/components/modifiers/enable-tooltip-test.ts
tests/integration/components/o-s-s/copy-test.ts
tests/test-helper.ts

Enable-tooltip tests & custom assertion.
Related to: https://github.com/upfluence/backlog/issues/1801

Enable-tooltip tests & custom assertion

---

addon/modifiers/enable-tooltip.ts

Fix tooltip not disappearing
Related to: https://github.com/upfluence/cs/issues/993

Fix tooltip not disappearing

---

addon/utils/easter-eggs.ts
app/styles/core-v2/_typography.less
app/styles/core/_typography.less
app/utils/easter-eggs.js

Update body color + bonus for easter eggs ;)

Update body color + bonus ;)

---

addon/components/o-s-s/currency-input.hbs
addon/components/o-s-s/currency-input.stories.js
addon/components/o-s-s/currency-input.ts
tests/dummy/app/templates/application.hbs
tests/integration/components/o-s-s/currency-input-test.ts

currency-input: add support placeholder and for disabling the currency value update

currency-input: add support placeholder and for disabling the currency value update

---

app/styles/base/_badge.less
app/styles/base/_buttons.less
app/styles/base/_slider.less
app/styles/base/_stats.less
app/styles/core-v2/_shims.less
app/styles/core-v2/_typography.less
app/styles/core/_typography.less
app/styles/currency-input.less
app/styles/utilities/_typography.less

Alias bold to semibold (and change wherever possible right now)
Related to: https://github.com/upfluence/backlog/issues/1807

Alias bold to semibold (and change wherever possible right now)

---

app/styles/base/_checkboxes.less

Fixes checkbox alignment
Related to: #https://github.com/upfluence/backlog/issues/2350

Fixes checkbox alignment

---

addon/components/o-s-s/banner.hbs
addon/components/o-s-s/checkbox.hbs
addon/components/o-s-s/checkbox.stories.js
addon/components/o-s-s/checkbox.ts
app/styles/base/_checkboxes.less
tests/dummy/app/controllers/application.js
tests/dummy/app/templates/application.hbs
tests/integration/components/o-s-s/checkbox-test.ts

Add partial as checkbox argument. Clean up & adjust the css class for size. Update tests and documentation
Related to: https://github.com/upfluence/backlog/issues/2327

Add partial as checkbox argument & tests & doc

---

addon/components/o-s-s/select.hbs
addon/components/o-s-s/select.ts
tests/integration/components/o-s-s/select-test.ts

Fix items not being updated after a search

Fix items not being updated after a search

---

addon/components/o-s-s/button-dropdown.hbs
addon/components/o-s-s/button-dropdown.ts
addon/modifiers/on-click-outside.js
app/styles/molecules/button-dropdown.less

Add useCapture arg to the on-click-outside modifier + various changes

Add useCapture arg to the on-click-outside modifier + various changes

---

addon/components/o-s-s/upload-area.hbs
addon/components/o-s-s/upload-area.stories.js
addon/components/o-s-s/upload-area.ts
addon/components/o-s-s/upload-item.stories.js
addon/components/o-s-s/upload-item.ts
tests/integration/components/o-s-s/upload-item-test.ts

Add new args for upload-area & upload-item
Related to: https://github.com/upfluence/backlog/issues/2366

Add new args for upload-area & upload-item

---

addon/components/o-s-s/password-input.hbs

Add: autocomplete on password-input

Add: autocomplete on password-input

---

addon/components/o-s-s/button.stories.js
addon/components/o-s-s/button.ts
addon/components/o-s-s/link.ts
app/styles/atoms/button.less
app/styles/base/_buttons.less
tests/dummy/app/templates/application.hbs
tests/integration/components/o-s-s/button-test.ts

Remove padding for tertiary skin button
Related to: #

[Tertiary btn] Remove padding for tertiary button

---

app/styles/core-v2/_variables.less
app/styles/molecules/navigation.less
app/styles/oss-components.less

Adds support for new navigations classes.

New navigation classes

---

.github/workflows/ci.yml

Run CI on PR branches and Release tags only

Run CI on PR branches and Release tags only

---

addon/components/o-s-s/skeleton.hbs
addon/components/o-s-s/skeleton.stories.js
addon/components/o-s-s/skeleton.ts
app/components/o-s-s/skeleton.js
tests/dummy/app/templates/application.hbs
tests/integration/components/o-s-s/skeleton-test.ts

Add new component OSS::Skeleton
Related to: [#ENG-510](https://linear.app/upfluence/issue/ENG-510/ossskeleton)
https://github.com/upfluence/oss-components/assets/111493996/6ec8cf16-e6f4-4c65-9432-a3cbada69469

Add: OSS::Skeleton component

---

addon/components/o-s-s/togglable-section.hbs
addon/components/o-s-s/togglable-section.stories.js
addon/components/o-s-s/togglable-section.ts
app/styles/molecules/togglable-section.less
app/styles/oss-components.less
tests/dummy/app/controllers/application.js
tests/dummy/app/templates/application.hbs
tests/integration/components/o-s-s/togglable-section-test.ts

Update OSS::TogglableSection UI and add an option to display FA icons

ENG-485: Update OSS::TogglableSection UI and add an option to display FA icons

---

addon/components/o-s-s/access-panel.hbs
addon/components/o-s-s/access-panel.ts
app/styles/organisms/access-panel.less

Animation support to the access panel component

Access panel: animation support

---

addon/components/o-s-s/button-dropdown.hbs
addon/components/o-s-s/button-dropdown.stories.js
addon/components/o-s-s/button-dropdown.ts
app/styles/molecules/button-dropdown.less
tests/dummy/app/templates/application.hbs
tests/integration/components/o-s-s/button-dropdown-test.ts

Related to:[ #ENG-473](https://linear.app/upfluence/issue/ENG-473/make-buttondropdown-entirely-clickable)

Dropdown button: Add mainAction & update component

---

addon/components/o-s-s/button.stories.js
addon/components/o-s-s/button.ts
app/styles/atoms/button.less
app/styles/core-v2/_colors.less

New css gradient variables 
Related to: [#ENG-609](https://linear.app/upfluence/issue/ENG-609/[gw][oss]-add-new-skins-and-colors)

New gradient css variable

---

app/styles/utilities/_borders.less
app/styles/utilities/_flex.less
app/styles/utilities/_flex.stories.mdx

Add flex col & row reverse classes
Related to: https://linear.app/upfluence/issue/ENG-634/information-message-not-in-charge-of-payment-[converted-to-information

Add flex col & row reverse classes

---

addon/components/o-s-s/tag.stories.js
addon/components/o-s-s/tag.ts
app/styles/base/_tags.less
app/styles/core-v2/_colors.less

tags: add primary-gradient skin
Related to: #

tags: add primary-gradient skin

---

addon/helpers/format-numeric.ts
app/helpers/format-numeric.js
tests/integration/components/o-s-s/skeleton-test.ts

Update format-numeric helper. Move code in `app` to `addon` file
Related to: https://linear.app/upfluence/issue/ENG-1019/update-full-limit-export-handling

Update format-numeric helper

---

addon/components/o-s-s/currency-input.hbs
addon/components/o-s-s/currency-input.ts
tests/integration/components/o-s-s/currency-input-test.ts

https://github.com/upfluence/oss-components/assets/111493996/aa9da0e1-b43e-48a1-bcc2-e5aabd5bbfc1
Related to: #[ENG-1296](https://linear.app/upfluence/issue/ENG-1296/character-for-0-on-extra-payments-healthy-nutrition-group)

Allow copy/paste on currency-input

---

app/styles/molecules/nav-tab.less

Selected nav-tab color update
Related to: https://linear.app/upfluence/issue/ENG-1407/[plg]-the-selected-tab-title-in-saved-search-has-wrong-color

Selected nav-tab color update

---

addon/components/o-s-s/password-input.hbs
addon/components/o-s-s/password-input.ts
translations/en-us.yaml

It adds a class to fix the background color on password input.
Related to: #
https://linear.app/upfluence/issue/ENG-1426/password-field-empty-state-is-super-confusing

Added upf-input class to password input

---

addon/components/o-s-s/copy.hbs
addon/components/o-s-s/copy.stories.js
addon/components/o-s-s/copy.ts
app/styles/atoms/copy.less
app/styles/oss-components.less
tests/dummy/app/templates/application.hbs
tests/integration/components/o-s-s/button-test.ts
tests/integration/components/o-s-s/copy-test.ts

It adds the inline attribute to copy component & related changes.
Related to: #
https://linear.app/upfluence/issue/ENG-1556/[oss-components]-osscopy-updated
https://www.loom.com/share/ffd978744530485dbec2a7759cdb1e48?sid=99516a38-df65-4110-96d9-f973d4524282

Updated OSS::Copy component

---

addon/components/o-s-s/attribute/country.hbs
addon/components/o-s-s/attribute/country.stories.js
addon/components/o-s-s/attribute/country.ts
addon/components/o-s-s/copy.hbs
app/components/o-s-s/attribute/country.js
app/styles/atoms/attribute.less
app/styles/atoms/copy.less
app/styles/oss-components.less
app/templates/components/upf-stat.hbs
app/templates/components/upf-table.hbs
tests/dummy/app/templates/application.hbs
tests/integration/components/o-s-s/attribute/country-test.ts
translations/en-us.yaml
yarn.lock

Added: OSS::Attribute::Country component + tests
Also defines base classes for other Attribute components

Added: OSS::Attribute::Country component + tests

---

app/styles/atoms/button.less

oss/buttons: more precise transitions

oss/buttons: more precise transitions

---

app/styles/organisms/attributes-panel.less

Improve padding in attribute panel
Related to: William request

Improve padding in attribute panel

---

addon/components/o-s-s/banner.hbs
addon/components/o-s-s/banner.stories.js
app/styles/banner.less
tests/integration/components/o-s-s/banner-test.ts

Related to: #[ENG-108](https://linear.app/upfluence/issue/ENG-108/paymentrequestpaymentmethodsummary-component)

Banner: Add a disable state

---

addon/components/o-s-s/star-rating.hbs
addon/components/o-s-s/star-rating.ts
tests/dummy/app/controllers/application.js
tests/dummy/app/templates/application.hbs
tests/integration/components/o-s-s/star-rating-test.ts

Fixed: OSS::StarRating onClick not triggered + added tests

Fixed: OSS::StarRating onClick not triggered + added tests

---

addon/components/upf-stat.js
app/styles/base/_stats.less
app/templates/components/upf-stat.hbs
app/templates/components/upf-table/header-cell.hbs

Replace old tooltip by new one
Related to: https://linear.app/upfluence/issue/ENG-168/tooltip-replace-legacy-tooltips

[Cooldow] Replace old tooltip by new one

---

addon/components/o-s-s/progress-bar.hbs
addon/components/o-s-s/progress-bar.stories.js
addon/components/o-s-s/progress-bar.ts
app/components/o-s-s/progress-bar.js
app/styles/atoms/progress-bar.less
app/styles/molecules/progress-bar.less
app/styles/oss-components.less
tests/dummy/app/templates/application.hbs
tests/integration/components/o-s-s/progress-bar-test.ts

It adds a new OSS::ProgressBar component
Related to: #
https://linear.app/upfluence/issue/ENG-509/get-rid-of-upf-progress-ossprogressbar

Added OSS::ProgressBar

---

addon/components/o-s-s/banner.hbs
addon/components/o-s-s/banner.stories.js
addon/components/o-s-s/banner.ts
app/styles/banner.less
tests/dummy/app/templates/application.hbs
tests/integration/components/o-s-s/banner-test.ts

Updated: OSS::Banner component with new size option + code cleanup

Updated: OSS::Banner component with new size option + code cleanup

---

addon/components/o-s-s/email-input.stories.js
addon/components/o-s-s/email-input.ts
tests/integration/components/o-s-s/email-input-test.ts

Update email regex to accept uppercase & tests
Related to: https://linear.app/upfluence/issue/ENG-1791/[plg]-cant-register-with-email-that-has-uppercase-letters

Update email regex to accept uppercase & tests

---

addon/components/o-s-s/banner.hbs
addon/components/o-s-s/banner.stories.js
app/styles/core-v2/_variables.less
tests/integration/components/o-s-s/banner-test.ts

OSS::Banner: rename title named block to title-suffix

OSS::Banner: rename title named block to title-suffix

---

addon/components/o-s-s/anchor.hbs
addon/components/o-s-s/anchor.stories.js
addon/components/o-s-s/anchor.ts
addon/components/o-s-s/layout/sidebar.hbs
addon/components/o-s-s/layout/sidebar/item.hbs
addon/components/o-s-s/layout/sidebar/item.stories.js
addon/components/o-s-s/layout/sidebar/item.ts
addon/components/o-s-s/star-rating.hbs
app/components/o-s-s/anchor.js
app/styles/organisms/sidebar.less
tests/integration/components/o-s-s/anchor-test.ts
tests/integration/components/o-s-s/layout/sidebar/item-test.ts

Related to: #[VEL-959](https://linear.app/upfluence/issue/VEL-959/cant-open-sidebar-and-settings-menu-content-in-a-separate-browser)

New component OSS::Anchor

---

index.js

ResolvePackagePath: ensure the project is pnpm compatible
No error on bootstrap import for standalone project on pnpm

ResolvePackagePath: ensure the project is pnpm compatible

---

app/styles/core-v2/_typography.less
app/styles/organisms/modal-dialog.less
app/styles/organisms/table.less

Add font-weight-semibold CSS variable

Add font-weight-semibold CSS variable

---

addon/components/o-s-s/banner.stories.js
addon/components/o-s-s/banner.ts
app/styles/banner.less
tests/integration/components/o-s-s/banner-test.ts

Align the banner size with the design system

Align the banner size with the design system

---

addon/components/o-s-s/currency-input.ts

Adds Czech Koruna currency to OSS::CurrencyInput

Adds Czech Koruna currency to OSS::CurrencyInput

---

addon/components/o-s-s/layout/navbar/nav-item.hbs
addon/components/o-s-s/layout/navbar/nav-item.stories.js
addon/components/o-s-s/layout/navbar/nav-item.ts
app/components/o-s-s/layout/navbar/nav-item.js
app/styles/nav-item.less
app/styles/oss-components.less
tests/dummy/app/templates/application.hbs
tests/integration/components/o-s-s/layout/navbar/nav-item-test.ts

It adds a new OSS::Layout::Navbar::NavItem component for use in the follow up email project 
Related to: #
https://linear.app/upfluence/issue/DRA-509/[oss-components]-new-sidenavbar-item

feat: added navbar item with test & storybook story

---

app/styles/molecules/navigation.less

Fix vertical line for navigation

Fix vertical line for navigation

---

addon/components/o-s-s/access-panel.hbs
addon/components/o-s-s/access-panel.ts
tests/integration/components/o-s-s/access-panel-test.ts

Autofocus on search in access panel

Autofocus on search in access panel

---

addon/components/o-s-s/modal-dialog.hbs
addon/components/o-s-s/modal-dialog.ts
addon/components/o-s-s/private/base-modal.ts
addon/components/o-s-s/split-modal.hbs
addon/components/o-s-s/split-modal.ts

Ensure only clicks initially initiated from outside the modal are counted as click-outside

Modals: Ensure only clicks initially initiated from outside the modal are counted as click-outside

---

app/styles/base/_floating-menu.less
app/styles/base/_infinite-select.less
app/styles/power-select.less

Fix OSS::Power select overflow & floating menu max-height

Fix OSS::Power select overflow & floating menu max-height

---

app/styles/shims/_all.less
app/styles/utilities/_typography.less

Remove old less variables for brand color

Remove old less variables for brand color

---

.prettierrc.js
addon/components/o-s-s/dialog.hbs
addon/components/o-s-s/dialog.stories.js
addon/components/o-s-s/dialog.ts
addon/components/o-s-s/modal-dialog.hbs
addon/components/o-s-s/private/base-modal.ts
addon/components/o-s-s/split-modal.hbs
app/components/o-s-s/dialog.js
app/styles/organisms/dialog.less
app/styles/oss-components.less
tests/dummy/app/controllers/application.js
tests/dummy/app/templates/application.hbs
tests/integration/components/o-s-s/dialog-test.ts

New basic dialog to confirm a user's action:

Added: New OSS::Dialog component

---

.gitignore
Makefile
index.js
package.json
pnpm-lock.yaml
scripts/generate_sonar_report
sonar-project.properties
tests/test-helper.ts

Enable sonarqube on oss-components

Enable sonarqube on oss-components

---

addon/components/o-s-s/layout/sidebar/item.hbs
addon/components/o-s-s/layout/sidebar/item.ts

Remove locked security for link anchor in sidebar item

[locked-state] Remove locked security for link anchor in sidebar item

---

addon/components/o-s-s/copy.hbs
addon/components/o-s-s/copy.ts
tests/integration/components/o-s-s/copy-test.ts

OSS::Copy: render nothing if the clipboard-write permission isn't granted

OSS::Copy: render nothing if the clipboard-write permission isn't granted

---

addon/components/o-s-s/infinite-select.hbs
addon/components/o-s-s/infinite-select.ts
addon/components/o-s-s/power-select.hbs
addon/components/o-s-s/select.hbs
app/styles/base/_infinite-select.less

Enable keyboard navigation on OSS::PowerSelect & OSS::Select

Enable keyboard navigation on OSS::PowerSelect & OSS::Select

---

addon/components/o-s-s/currency-input.ts

Related to: #[DRA-1343](https://linear.app/upfluence/issue/DRA-1343/remove-rub-currency-from-the-platform) & #[DRA-1417](https://linear.app/upfluence/issue/DRA-1417/add-malaysian-ringgits-to-currency-choices)
Removed RUB currency and replaced it by MYR.

Replace: currency RUB for MYR

---

addon-test-support/index.ts
addon-test-support/setup-clipboard.ts
addon/components/o-s-s/copy.ts
addon/components/o-s-s/modal-dialog.hbs
addon/components/o-s-s/modal-dialog.stories.js
addon/components/o-s-s/modal-dialog.ts
addon/components/o-s-s/upload-item.ts
tests/integration/components/o-s-s/copy-test.ts
tests/integration/components/o-s-s/modal-dialog-test.ts

- Properly format uploaded file name (clear escape characters)
- Fix copy button not appearing on firefox/safari
- Add support for icon in modal dialog

Properly format uploaded file name (clear escape characters)

---

.github/workflows/ci.yml

ci: add webfactory/ssh-agent step to release job

ci: add webfactory/ssh-agent step to release job

---

addon/components/o-s-s/side-panel.stories.js
app/styles/core/_typography.stories.mdx

Fix: sidepanel main named block and header class names

---

addon/modifiers/Modifiers.stories.mdx
addon/modifiers/enable-input-autofocus.stories.js
addon/modifiers/enable-input-autofocus.ts
app/modifiers/enable-input-autofocus.js
tests/integration/components/modifiers/enable-input-autofocus-test.ts

Related to: #[VEL-3542](https://linear.app/upfluence/issue/VEL-3542/create-autofocus-modifier)
https://www.loom.com/share/ea9dd0960ade47d99ec0df63e5c00984?sid=74e0cee2-e512-4656-94dc-daaaf3322b6e

Added input autofocus modifier

---

addon/components/o-s-s/side-panel.hbs
app/styles/organisms/side-panel.less
tests/dummy/app/templates/application.hbs
tests/integration/components/o-s-s/side-panel-test.ts

- Added <:global> named block to SidePanel component so we can easily use the sidepanel with an {{outlet}}
- Fixed issue on CSS class name
- Added test on <:global> named block

Added: sidepanel global named block and fixed css

---

app/styles/core/_colors.less

Add font color class for instagram accent

Add font color class for instagram accent

---

addon/components/o-s-s/illustration.hbs
addon/components/o-s-s/illustration.ts
addon/components/o-s-s/infinite-select.hbs
tests/integration/components/o-s-s/illustration-test.ts
tests/integration/components/o-s-s/infinite-select-test.js

Remotely fetch the SVG asset before usage. Ensures it's ready when style is applied.

Fix OSS::Illustration CSS vars

---

addon/components/o-s-s/input-container.hbs
addon/components/o-s-s/input-container.stories.js
addon/components/o-s-s/input-container.ts
addon/components/o-s-s/input-group.hbs
addon/components/o-s-s/input-group.stories.js
addon/components/o-s-s/input-group.ts
addon/components/o-s-s/slider.hbs
addon/components/o-s-s/slider.stories.js
addon/components/o-s-s/slider.ts
app/styles/base/_slider.less
tests/dummy/app/controllers/application.js
tests/dummy/app/templates/application.hbs
tests/integration/components/o-s-s/slider-test.ts

- OSS::Slider update to support correct input (with animation)
- Add `@type` of OSS::InputContainer & OSS::InputGroup

OSS::Slider update & DRA-1529

---

addon/components/o-s-s/button-dropdown.hbs
addon/components/o-s-s/button-dropdown.stories.js
addon/components/o-s-s/button-dropdown.ts
addon/components/o-s-s/button.ts
app/styles/molecules/button-dropdown.less
tests/integration/components/o-s-s/button-dropdown-test.ts

https://www.loom.com/share/079b104057cb4022a92a04fdfa4e2055
Related to: #

Added square arg to OSS::ButtonDropdown

---

addon/components/o-s-s/slider.hbs
app/styles/base/_toggle-switch.less
app/styles/toggle-switch.less
tests/dummy/app/controllers/actionable.ts
tests/dummy/app/router.js
tests/dummy/app/routes/actionable.ts
tests/dummy/app/templates/actionable.hbs
tests/dummy/app/templates/application.hbs
tests/dummy/app/templates/index.hbs

Related to: #[DRA-1572](https://linear.app/upfluence/issue/DRA-1572/incorrect-toggle-button-design)
Update css to match ui kit v2
Default
Hover
Active
Disabled

ToggleSwitch: Rework component to match ui kit v2

---

addon/components/o-s-s/select.hbs

Related to: #[DRA-1708](https://linear.app/upfluence/issue/DRA-1708/[oss-componentsember-influencerpublishr-admin-web]-add-ellipsis-when)

Select: Better format selected value (ellipsis)

---

addon/components/o-s-s/avatar.ts
tests/integration/components/o-s-s/avatar-test.ts

I passed from tracked to getter in order to manage changes that would occur on args 
Related to: #

fix: added getter for display initials in oss::avatar

---

addon/components/o-s-s/tag.ts

This PR exports Tag component's arguments to be used in facade-web's new BehaviourSwitch

exporting tag arguments

---

addon/components/o-s-s/power-select.ts
addon/components/o-s-s/private/base-dropdown.ts
addon/components/o-s-s/select.ts
addon/utils/attach-dropdown.ts

Attach dropdown placement

---

app/styles/oss-components.less
app/styles/shims/bootstrap.less

Expose Bootstrap imports explicitly so we can gradually remove what we don't need until we are all free of it.

Expose Bootstrap imports explicitly

---

addon-test-support/setup-clipboard.ts
addon/components/o-s-s/password-input.ts
addon/components/o-s-s/progress-bar.ts
addon/components/o-s-s/skeleton.ts
addon/components/o-s-s/slider.ts
tests/integration/components/o-s-s/password-input-test.ts
tests/integration/components/o-s-s/side-panel/header-test.ts
tests/test-helper.ts

- Setup clipboard hooks typing update
- Fixes a couple console warnings in tests about html safety

Setup clipboard hooks typing update

---

addon/components/o-s-s/slider.stories.js

- Fix `OSS::Slider` story rendering
- Add `inputOptions` to `OSS::Slider` story

Fix OSS::Slider doc rendering

---

tests/dummy/config/targets.js

Stop supporting IE11

---

config/ember-try.js

Added fix for jquery-integration depreciation

---

addon/components/input-wrapper.js
addon/components/upf-stat.js
app/templates/components/input-wrapper.hbs
app/templates/components/upf-stat.hbs

Class name bindings deprecation

[Cooldown] Class name bindings deprecation

---

addon/components/o-s-s/power-select.hbs
addon/components/o-s-s/private/base-dropdown.ts
addon/components/o-s-s/select.hbs

https://www.loom.com/share/f5af7c1cd4c94c1e950badf6ef770bb6?sid=bd09c609-c4f8-4087-b009-af4b51c9de89
Related to: #
Added useCapture to manage event stop propagation in a way that works properly for all dropdowns on the table. 
Bonus: It fixes issues where dropdowns are visible when a sidepanel is toggled 🎉

Added fix for captureClickOutside

---

addon/components/o-s-s/pulsating-dot.hbs
addon/components/o-s-s/pulsating-dot.stories.js
addon/components/o-s-s/pulsating-dot.ts
app/components/o-s-s/pulsating-dot.js
app/styles/atoms/pulsating-dot.less
app/styles/oss-components.less
tests/dummy/app/templates/visual.hbs
tests/integration/components/o-s-s/pulsating-dot-test.ts

Adds:
- a new `OSS::PulsatingDot` component which has a single `skin` argument
- related less file using less functions to generate the proper colors for the component & keyframes
- related tests
- related storybook entry
https://github.com/user-attachments/assets/ffd6e056-dc69-44a0-ac39-7027f0729e39

OSS::PulsatingDot component

---

addon/components/o-s-s/search-field.hbs
addon/components/o-s-s/search-field.stories.js
addon/components/o-s-s/search-field.ts
app/components/o-s-s/search-field.js
tests/dummy/app/controllers/input.ts
tests/dummy/app/templates/input.hbs
tests/integration/components/o-s-s/search-field-test.ts
translations/en-us.yaml

Create a dedicated OSS::SearchField component

Create a dedicated OSS::SearchField component

---

addon/components/o-s-s/toggle-switch.hbs
app/styles/base/_toggle-switch.less
app/styles/toggle-switch.less

Update toggle switch component with a check icon on active state
Related to: #

Update toggle switch component with a check icon on active state

---

addon/components/o-s-s/email-input.stories.js
addon/components/o-s-s/email-input.ts

Standardize email inputs placeholders from `john.doe@example.com` to `Enter your email`

Update email-input component's placeholder

---

addon/components/o-s-s/attributes-panel.stories.js
addon/components/o-s-s/attributes-panel.ts
tests/integration/components/o-s-s/attributes-panel-test.ts

Update attributes panel component to handle initial mode
Related to: https://github.com/upfluence/ember-influencer/pull/733

Update attributes panel component to handle initial mode

---

addon/components/o-s-s/button-dropdown.hbs
app/styles/molecules/button-dropdown.less
tests/integration/components/o-s-s/button-dropdown-test.ts

Add states for dropdown button

Add states for dropdown button

---

addon/components/o-s-s/access-panel.hbs
addon/components/o-s-s/access-panel.ts
addon/components/o-s-s/infinite-select.hbs
addon/components/o-s-s/infinite-select.ts
addon/components/o-s-s/search-field.hbs
addon/components/o-s-s/search-field.stories.js
addon/components/o-s-s/search-field.ts
addon/utils/keyboard.ts
app/utils/keyboard.js
tests/integration/components/o-s-s/access-panel-test.ts

Update Search component Field to handle a type and use it instead of Input Container in Infininte Select and Access Panel

Update searchfield component to use it where needed

---

addon/components/o-s-s/access-panel.stories.js

Add docs for AccessPanel component
Related to: #

Add docs for AccessPanel component

---

addon/components/o-s-s/form.hbs
addon/components/o-s-s/form.ts
addon/helpers/form-field-feedback.ts
addon/modifiers/register-form-field.ts
addon/modifiers/required-input.ts
addon/services/form-manager.ts
app/components/o-s-s/form.js
app/helpers/form-field-feedback.js
app/modifiers/register-form-field.ts
app/modifiers/required-input.js
app/services/form-manager.js
package.json
pnpm-lock.yaml
tests/integration/components/o-s-s/avatar-group-test.ts
tests/integration/components/o-s-s/form-test.ts
tests/integration/helpers/form-field-feedback-test.ts
tests/integration/modifiers/register-form-field-test.ts
tests/unit/services/form-manager-test.ts
translations/en-us.yaml

Add support for OSS::Form component & backing FormManager service.
These two work together to properly handle forms and their validation behaviours via validator functions that are setup for fields.
In addition to them, we also have:
- a modifier allowing us to define a new field into a form along w/ its validator function
- a helper allowing us to get the current feedback set for a given field (if any)

Add support for OSS::Form component & backing FormManager service

---

addon/components/o-s-s/upload-area.hbs
app/styles/molecules/upload-area.less
tests/integration/components/o-s-s/upload-area-test.ts

Fixing overflowing illustration image on Uploader on small screens

Make upload area (lg) responsive

---

addon/components/o-s-s/button.ts
addon/components/o-s-s/smart/button.hbs
addon/components/o-s-s/smart/button.stories.js
addon/components/o-s-s/smart/button.ts
addon/components/o-s-s/smart/toggle-buttons.ts
app/components/o-s-s/smart/button.js
app/styles/atoms/button.less
app/styles/core/_all.less
app/styles/core/_smart.less
tests/dummy/app/controllers/smart.ts
tests/dummy/app/templates/smart.hbs
tests/dummy/app/templates/visual.hbs
tests/integration/components/o-s-s/smart/button-test.ts

Added new OSS::Smart::Button component extending the original OSS::Button component with 2 new skins.
Related to: #[dra-3043](https://linear.app/upfluence/issue/DRA-3043/oss-components-smartbutton)

Added Smart Button component

---

addon/components/o-s-s/skeleton.ts
addon/components/o-s-s/smart/skeleton.hbs
addon/components/o-s-s/smart/skeleton.stories.js
addon/components/o-s-s/smart/skeleton.ts
app/components/o-s-s/smart/skeleton.js
app/styles/utilities/_loading.less
tests/dummy/app/templates/smart.hbs
tests/integration/components/o-s-s/smart/skeleton-test.ts

Added new Smart Skeleton component
Related to: #[dra-3036](https://linear.app/upfluence/issue/DRA-3036/oss-components-smartskeleton)
https://www.loom.com/share/e7ecb09e4b5041d9bae99626bd1c5aae

Added new Smart Skeleton component

---

addon/components/o-s-s/smart/input.hbs
addon/components/o-s-s/smart/input.stories.js
addon/components/o-s-s/smart/input.ts
app/components/o-s-s/smart/input.js
app/styles/atoms/smart-input.less
app/styles/core/_smart.less
tests/dummy/app/controllers/smart.ts
tests/dummy/app/templates/smart.hbs
tests/integration/components/o-s-s/smart/input-test.ts

Related to: #
https://www.loom.com/share/64dac0060cd845488aeb4cd265466512?sid=ed824c2f-c79f-4284-8fa5-d37a13fabff6

Added Smart::Input component

---

addon/components/o-s-s/smart/feedback.hbs
addon/components/o-s-s/smart/feedback.stories.js
addon/components/o-s-s/smart/feedback.ts
app/components/o-s-s/smart/feedback.js
app/styles/atoms/smart-feedback.less
app/styles/core/_smart.less
app/styles/deprecated/_fonts.less
tests/dummy/app/controllers/smart.ts
tests/dummy/app/templates/smart.hbs
tests/integration/components/o-s-s/smart/feedback-test.ts

Related to: 
Smart Feedback component which uses a loading argument to toggle different states. 
- Added Smart Feedback component
- with icon named block as the blob isn't supposed to be in this project 
https://www.loom.com/share/b7d7469e042a4f12adaf719e18b3e120?sid=e20bbeb4-82b4-4a7e-ab1e-d03d4e6f90c2

OSS::Smart::Feedback

---

addon/components/o-s-s/scrollable-panel.stories.js
addon/components/o-s-s/scrollable-panel.ts
tests/integration/components/o-s-s/scrollable-panel-test.ts

Related to: #
Add a new offset attribute on scrollable panel:
- Allow to displays shadows when the scroll offset has been reached
https://github.com/user-attachments/assets/274932c3-a456-43a8-b644-1b354f58d23e

Scrollable-panel: Add new offset params

---

addon/components/o-s-s/smart/tag-input.hbs
addon/components/o-s-s/smart/tag-input.stories.js
addon/components/o-s-s/smart/tag-input.ts
addon/components/o-s-s/smart/tag.hbs
addon/components/o-s-s/smart/tag.stories.js
addon/components/o-s-s/smart/tag.ts
app/components/o-s-s/smart/tag-input.js
app/components/o-s-s/smart/tag.js
app/styles/atoms/smart/tag-input.less
app/styles/atoms/smart/tag.less
app/styles/oss-components.less
tests/dummy/app/controllers/smart.ts
tests/dummy/app/templates/smart.hbs
tests/integration/components/o-s-s/smart/tag-input-test.ts
tests/integration/components/o-s-s/smart/tag-test.ts
translations/en-us.yaml

Related to: #[dra-3042](https://linear.app/upfluence/issue/DRA-3042/oss-components-smarttag-and-smarttaginput)

Added Smart::Tag & Smart::TagInput components

---

addon/components/o-s-s/tip.hbs
addon/components/o-s-s/tip.stories.js
addon/components/o-s-s/tip.ts
app/components/o-s-s/tip.js
app/styles/atoms/tip.less
app/styles/oss-components.less
tests/integration/components/o-s-s/tip-test.ts

Creates a Tip component
Related to: #5888

Create OSS::Tip component

---

addon/components/o-s-s/pill.hbs
addon/components/o-s-s/pill.stories.js
addon/components/o-s-s/pill.ts
addon/components/o-s-s/smart/pill.hbs
addon/components/o-s-s/smart/pill.stories.js
addon/components/o-s-s/smart/pill.ts
addon/utils/run-smart-gradient-animation.ts
app/components/o-s-s/charger.js
app/components/o-s-s/pill.js
app/components/o-s-s/smart/charger.js
app/components/o-s-s/smart/pill.js
app/styles/animations/smart-rotating-gradient.less
app/styles/atoms/pill.less
app/styles/atoms/smart/pill.less
app/styles/oss-components.less
tests/dummy/app/controllers/visual.ts
tests/dummy/app/templates/visual.hbs
tests/integration/components/o-s-s/pill-test.ts
tests/integration/components/o-s-s/smart/pill-test.ts

Backport oss::pill & oss::smart::pill component

---

app/styles/base/_inputs.less
app/styles/core/_form.less
app/styles/deprecated/_typography.less

Add label element style to improve consistency across forms.
Related to: #

Add label element style

---

addon/components/o-s-s/smart/immersive/input.stories.js
addon/components/o-s-s/smart/immersive/logo.hbs
addon/components/o-s-s/smart/immersive/logo.stories.js
addon/components/o-s-s/smart/immersive/logo.ts
addon/components/o-s-s/smart/immersive/select.stories.js
addon/components/o-s-s/smart/immersive/select.ts
addon/services/wizard-manager.ts
app/styles/atoms/smart/immersive-select.less
app/styles/atoms/smart/logo.less
app/styles/base/_infinite-select.less
tests/dummy/app/controllers/smart.ts
tests/dummy/app/templates/smart.hbs
tests/integration/components/o-s-s/smart/immersive/logo-test.ts
tests/integration/components/o-s-s/smart/immersive/select-test.ts

Modifications:
- Smart::Logo
- New `@hasError` parameter
- use more specific class names to prevent css collisions in other projects using the same class names
- Immersive::Select
- height fix when multiple elements are in the container
- auto close dropdown when in single mode
- left align dropdown (bottom & top placements)
- adjust CSS
- Adjust storybook names for some smart components
- WizardManager
- Prevent the error manager from focusing on the current step when it's in focus

Minor tweaks & improvements to Smart components

---

addon/components/o-s-s/form.stories.js
addon/helpers/Helpers.stories.mdx
addon/helpers/form-field-feedback.stories.js
addon/modifiers/register-form-field.stories.js
tests/dummy/app/controllers/input.ts
tests/dummy/app/templates/input.hbs

Document `OSS::Form`, `register-form-field` modifier and `form-field-feedback` helper
Related to: #5543

Document OSS::Form & its companions (service, modifier, helper)

---

app/styles/atoms/avatar.less
app/styles/organisms/sidebar.less

Fix UI for sidebar. For the avatar initial font-size, I check with Hsinyi for that

Fix UI for sidebar
