upfluence/oss-components

- addon/components/destructive-button.js
- addon/components/loading-button.js
Currently the `disabled` state is never removed after the resolving of the promise due to an none update of the  `shouldBeDisabled` proprety. I'm not really sure on what going wrong, but I have use an observer to set the `disabled` which will make the thing work.
@AlexisMontagne @phndiaye If you have some insight on it.
> Fix disabled

- addon/mixins/upf-table-search.js
In case of `searchAttribute` is linked to a relation, the itemName can be empty (if not loaded yet) and this lead to an error with the `toLowerCase` on a `null` value.
https://sentry.io/upfluence/inbox-web/issues/452088331/?query=is:unresolved
> Fix toLowerCase issue

- addon/components/upf-stat.js
- app/templates/components/upf-stat.hbs
Related: https://github.com/upfluence/oss/pull/56
> Add support for inline icons (after the data) in upf-stat

- addon/components/radio-button.js
While loading if disabled is true, then don't show the isChecked state as well till it is not disabled anymore. 
Wanting to use this for analytics-web because it takes a while for the following count on edit form to update to the correct value. So while it is updating, then i disable the radio buttons, until it is done updating then i enable it and show the correct selection type `currentType`.
> Allow disabled option for radio button segmented control

- .github/CODEOWNERS
- addon/components/upf-icon.js
Because the root path of the assets differs wether we are in an addon or an Ember application, this allows it to be overwritten where needed.
None
> Settable upf-icon assets root path

- addon/components/column-visibility-panel.js
- addon/components/upf-table/index.js
- app/components/column-visibility-panel.js
- app/templates/components/column-visibility-panel.hbs
- app/templates/components/upf-table.hbs
Related to: https://github.com/upfluence/backlog/issues/312
When the user opens the workflow column selector, it does not close if the user clicks outside this section. It is necessary to close the column selector if the user clicks outside this section (focus out).
> Oss components : upgrade column selection panel

- addon/components/app-header.js
- app/templates/components/app-header.hbs
Fixes logo URL after engine changes
Related to https://github.com/upfluence/backlog/issues/532
Clicking on Upfluence logo will redirect user to correct page
> Change logo url

- addon/components/destructive-button.js
- addon/components/expanding-search.js
- addon/components/loading-button.js
- addon/components/radio-button.js
- addon/components/upf-checkbox.js
- addon/components/upf-numeric-range.js
- addon/components/upf-slider.js
As we want to rollout `data-control-name` all around the soft, we start first by adding the `data-control-name` binding on all user actionable elements.
Relates to https://github.com/upfluence/backlog/issues/657
> Add a `data-control-name` attribute binding on all user-actionable elements

- addon/components/loading-button.js
Add support of bubbles for loading button to stop propagation of event
Related to: https://github.com/upfluence/backlog/issues/402
> Add support of bubbles for loading button

- addon/components/o-s-s/toggle-switch.hbs
- addon/components/o-s-s/toggle-switch.js
- app/styles/oss-components.less
- app/styles/toggle-switch.less
Adds the ability to pass "disabled" argument to the component.
Related to: https://github.com/upfluence/backlog/issues/732
> Added: ability to pass disabled argument to component

- addon/components/upf-table/index.js
Search queries were being processed too quickly which spams the API, debounce time was increased from 100ms to 500ms
Related to: https://app.zenhub.com/workspaces/engineering-60b8ff993afa1f000e7c1d9c/issues/upfluence/cs/236
No observable changes should be felt
> Increase debounce time

- addon/components/o-s-s/button.stories.js
- addon/components/o-s-s/button.ts
- addon/components/o-s-s/input-container.hbs
- addon/components/o-s-s/input-container.stories.js
- addon/components/o-s-s/input-container.ts
- addon/components/o-s-s/link.hbs
- addon/components/o-s-s/link.ts
- app/components/o-s-s/link.js
- tests/integration/components/o-s-s/button-test.js
- tests/integration/components/o-s-s/link-test.ts
- Adds a new component: OSS::Link for displaying transparent "buttons" that trigger actions.
- Adds `theme` argument to the OSS::Button component to control its display on dark backgrounds.
- Adds `disabled`. argument to OSS::InputContainer to disable the inner input easily without having having to pass an `input` named block.
> Add OSS::Link component and add args to OSS::Button & OSS::InputContainer

- addon/components/o-s-s/badge.stories.js
- addon/components/o-s-s/badge.ts
- tests/dummy/app/templates/application.hbs
- tests/integration/components/o-s-s/badge-test.ts
Add the `@skin` & `@plain` args to the OSS::Badge component
Related to: https://github.com/upfluence/backlog/issues/1195
> OSS::Badge: add support for skin and plain args

- addon/components/o-s-s/input-container.hbs
Fixed: OSS::InputContainer now fills all the available space
> Fixed: OSS::InputContainer now fills all the available space

- app/styles/toast.less
Add responsiveness for toasts for small screen
Related to: https://github.com/upfluence/backlog/issues/1663
> Add responsiveness for toasts

- addon/components/o-s-s/modal-dialog.ts
You live, you learn 😅 `.bind` function actually returns a new function wrapping the one it's attached to and i didn't know that. This was causing an issue when clearing the escape event listener because it's not the same function signature anymore.
> components/o-s-s/modal-dialog: prevent sneaky event listener not being removed

- addon/helpers/stop-propagation.ts
- app/helpers/stop-propagation.js
- tests/integration/helpers/stop-propagation-test.ts
Because it's something we have to do a lot, this helper will allow us to invoke `event.stopPropagation` directly from the templates.
Whilst this can be useless if we have an action defined in the component JS where we can handle the event, it can be useful when mutating props with `mut` or calling a parent-provided action:
-  `{{on "click" (fn (mut this.myProp) false)}}` ->  `{{on "click" (stop-propagation (fn (mut this.myProp) false))}}`
-  `{{on "click" @parentAction}}` -> `{{on "click" (stop-propagation @parentAction)}}`
> Add stop-propagation helper

- addon/components/o-s-s/code-block.hbs
- app/styles/code-block.less
- tests/dummy/app/templates/application.hbs
- tests/integration/components/o-s-s/phone-number-input-test.ts
OSS::CodeBlock copy button now has an opaque background to hide the text underneath.
> Fixed: OSS::CodeBlock copy button opaque background

- addon/components/o-s-s/link.hbs
- addon/components/o-s-s/link.stories.js
- addon/components/o-s-s/link.ts
- tests/integration/components/o-s-s/link-test.ts
Change a to div for OSS::Link. The `preventEvent` doesn't work when we pass an action with a `router.transitionTo` and use href link
Related to: https://github.com/upfluence/backlog/issues/936
> Change a to div for OSS::Link

- addon/components/o-s-s/country-selector.stories.js
- addon/components/o-s-s/country-selector.ts
- tests/integration/components/o-s-s/country-selector-test.ts
- translations/en-us.yaml
OSS::CountrySelector initial value triggers onChange + tests
Related to: #[1338](https://github.com/upfluence/backlog/issues/1338)
@initialValue triggers the onChange method to notify there is a match to the parent.
Tests updated & tests added for initialValue
> OSS::CountrySelector initial value triggers onChange + tests

- addon/helpers/transition-to.ts
- app/helpers/transition-to.js
- tests/integration/helpers/transition-to-test.ts
Because sometimes buttons or other components than LinkTo's do transitions to 😩 . and i was getting tired of creating actions on the JS just to do transitions.
Usage:
```hbs
<OSS::Button {{on "click" (transition-to "route.subroute")}} />
```
> Add transition-to helper

- addon/components/o-s-s/currency-input.hbs
- addon/components/o-s-s/currency-input.stories.js
- addon/components/o-s-s/currency-input.ts
- app/styles/currency-input.less
- tests/dummy/app/controllers/application.js
- tests/dummy/app/templates/application.hbs
- tests/integration/components/o-s-s/currency-input-test.ts
Add param on OSS::CurrencyInput for show only the currency dropdown without number input
Related to: none, advancement for replace in identity web
> Add param on OSS::CurrencyInput for show only the currency dd

- addon/components/o-s-s/array-input.hbs
- addon/components/o-s-s/power-select.hbs
- addon/components/o-s-s/power-select.ts
- app/styles/array-input.less
- app/styles/atoms/chip.less
- tests/dummy/app/controllers/application.js
- tests/dummy/app/templates/application.hbs
- tests/integration/components/o-s-s/array-input-test.js
- tests/integration/components/o-s-s/power-select-test.ts
Replace code in OSS::PowerSelect and OSS::ArrayInput for use OSS::Chip when you display the items
Related to: https://github.com/upfluence/backlog/issues/1706
We use OSS::Chip Component in selected-item name block of OSS::PowerSelect so OSS::PowerSelect didn't need the onChange(item, 'deletion') function anymore
> Use OSS::Chip in OSS::PowerSelect and OSS::ArrayInput

- .storybook/main.js
- addon/helpers/Helpers.stories.mdx
- addon/helpers/redirect-to.ts
- app/helpers/redirect-to.js
- tests/integration/components/o-s-s/link-test.ts
- tests/integration/helpers/redirect-to-test.ts
Add helper for running URL redirections just like a `window.open` would
> Add helper for running URL redirections

- addon/components/o-s-s/phone-number-input.hbs
- addon/components/o-s-s/phone-number-input.ts
- tests/integration/components/o-s-s/phone-number-input-test.ts
- translations/en-us.yaml
Allow the focus input (triggered when using autocompletion) to be handled, but add a validation to ensure that the user didn't type the country prefix in the phone numbeR.
> Phone input validation

- app/styles/base/_buttons.less
- app/styles/molecules/button-dropdown.less
Context: till now, the small button and the "normal" one were exactly the same, which is weird.
This PR uses 24px as height for the small one and deprecates the xs one (which we will keep until the transition to "sm" is finished).
Related to: https://github.com/upfluence/backlog/issues/1705
> Button size update

- addon/components/o-s-s/alert.hbs
- tests/dummy/app/templates/application.hbs
- tests/integration/components/o-s-s/alert-test.ts
Add named block `extra-content` for OSS::Alery
Related to: https://github.com/upfluence/backlog/issues/1811
> Add extra-content named block for OSS::Alert

- addon/components/o-s-s/alert.hbs
- addon/components/o-s-s/alert.stories.js
- addon/components/o-s-s/alert.ts
- app/styles/alert.less
- tests/dummy/app/templates/application.hbs
- tests/integration/components/o-s-s/alert-test.ts
The goal is to update the alert component to add 3 new props: A closable prop, a plain prop and a link prop (name block).
- Closable parameter, to delete the alert when you click on cross
- Plain parameter, for display a background-color white in the alert when it is false
- New name bloc named extra-content, which allow us to have some content in the alert like links
Related to: [#1811](https://github.com/upfluence/backlog/issues/1811)
Picture with plain equal false and closable equal true : 
Picture with extra content and default value for plain and closable:
> Update OSS::Alert component

- addon/components/o-s-s/modal-dialog.stories.js
- app/styles/modal-dialog.less
Handles the responsiveness of the ModalDialog components for mobile layout.
Related to: #[1945](https://github.com/upfluence/backlog/issues/1945)
Related to: #[827](https://github.com/upfluence/cs/issues/827)
Notes have been added to storybook to explain that:
- the footer defaults to `fx-row fx-gap-px-12` in desktop mode
- the footer defaults to `fx-col fx-gap-px-9` with column-reverse set in order to have our cancel buttons on the bottom of the options.
Here's an example render in creators-web : 
[Mobile mode]
[Unchanged Desktop mode]
FYI, in the offer-acceptance-modal in creators web; here are the changes made to have the proper layout:
[original footer code]
```
<:footer>
<div class="fx-row fx-1 fx-gap-px-12 fx-malign-end">
<OSS::Button .../>
<OSS::Button
@skin="primary" ..../>
</div> …
```
> Added: OSS::ModalDialog responsiveness

- app/styles/currency-input.less
The input showed the border red on focus even when not "errored"
Related to: #[2000](https://github.com/upfluence/backlog/issues/2000)
> Fixed: CurrencyInput error focus border

- index.js
- package.json
As defined in the following [RFC](https://rfcs.emberjs.com/id/0090-addon-tree-caching/), this adds caching to the addon when its tree in being built. At the moment, each apps or engine declaring `@upfluence/oss-components` as a dependency build its tree even if it's been done already by another app or engine.
> Addon tree caching setup

- .storybook/styles/stories/colors-v2.less
- app/styles/core-v2/_colors.less
- app/styles/core-v2/_colors.stories.mdx
Add new Instagram accent color:
- add `--color-instagram-accent` CSS variable
- add `.background-instagram-accent` class. I don't set `color` in the name because the color is apply on `background` and not `background-color`. `radial-gradient` only work in background attribute
- first time we use prettier on these files, ok 🤷‍♂️
Related to: Victor (see [OSS Tokens](https://www.figma.com/file/i92PsCj4g8zHhZ5OsrFAcV/1.0-OSS-Tokens-%F0%9F%8C%88) update)
> Add new Instagram accent color

- app/styles/modal-dialog.less
Removing ModalDialog responsiveness due to issues it creates with dropdowns inside the modals.
Related to: #[2021](https://github.com/upfluence/backlog/issues/2021)
> Removed ModalDialog responsiveness :(

- addon/components/o-s-s/alert.stories.js
- addon/components/o-s-s/alert.ts
- tests/integration/components/o-s-s/alert-test.ts
Adds support for telling the parent context that an alert has been closed.
> Alerts: allow an optional method to be called when the alert is closed

- addon/components/o-s-s/code-block.hbs
- app/styles/code-block.less
Updated: code block component visuals
Old visuals :
New visuals :
Related to: #https://github.com/upfluence/backlog/issues/2045
> Update Code-block component visuals

- .storybook/styles/stories/variables.less
- addon/components/expanding-search.hbs
- app/styles/array-input.less
- app/styles/atoms/button.less
- app/styles/base/_buttons.less
- app/styles/base/_datatables.less
- app/styles/base/_expanding-search.less
- app/styles/base/_inputs.less
- app/styles/core/_variables.less
- app/styles/core/_variables.stories.mdx
- app/styles/molecules/button-dropdown.less
Till now, we had an inconsistency on the `height` rule of multiple components including:
- buttons
- inputs
- components built on top of them
This PR makes sure that they all converge to using `36px` (from the 6px based grid).
Because some parts of the software use the `input-size-X` variables defined before, they have just been updated for now we remove all mention of them.
> Align buttons & inputs to the same height: 36px

- addon/components/o-s-s/select.hbs
- addon/components/o-s-s/select.stories.js
- tests/integration/components/o-s-s/select-test.ts
Add support for a named-block to display the selected item as currently only a string label is supported. This will allow us to have more visual selected items just like in the options.
> Add support for a named-block to display the selected item

- addon/components/o-s-s/alert.ts
Stop propagation of closable event. A bug appear when alert is in modal and close it too.
Related to: https://github.com/upfluence/backlog/issues/2166
> OSS::Alert - Stop propagation of closable event

- .storybook/main.js
- addon-test-support/custom-assertions/tooltip.stories.mdx
- addon-test-support/custom-assertions/tooltip.ts
- addon/modifiers/enable-tooltip.stories.js
- stories/Guidelines.stories.mdx
Add tooltip assertion documentation
Related to: https://github.com/upfluence/backlog/issues/1801
> Add tooltip assertion documentation

- addon/modifiers/enable-tooltip.ts
- addon/utils/dope.ts
- app/styles/layouts/_header.less
- Not launch a delay rendering if one is in progress
- Move logic event destroy in dedicated function
- In `dope.ts`, store height & width element to avoid distortion on the right and bottom of the view port
Related to: https://github.com/upfluence/backlog/issues/2273
Tooltip disappears.
> Fix tooltip not destroyed & distortion on right placement

- addon/components/o-s-s/upload-area.hbs
- addon/components/o-s-s/upload-item.hbs
- app/styles/core-v2/_typography.less
Add `fx-1` to fix text-ellipsis on upload-item.
Remove unnecessary class `allow-text-overflow-on-children`
Related to: https://github.com/upfluence/backlog/issues/2218
> Fix text-ellipsis on upload-item

- addon/components/o-s-s/upload-item.hbs
- addon/components/o-s-s/upload-item.ts
Fix preview in uploader not showing by using background-image
Related to: #https://github.com/upfluence/backlog/issues/2281
> Fix preview in uploader not showing

- addon/components/o-s-s/array-input.stories.js
- addon/components/o-s-s/array-input.ts
- tests/integration/components/o-s-s/array-input-test.js
Allow the `OSS::ArrayInput` component to receive extra keyboard event codes that can be used to validate an entry beside the default Enter one.
> components/oss/array-input: add support for extra keyboard triggers

- addon/components/o-s-s/modal-dialog.hbs
- addon/components/o-s-s/modal-dialog.stories.js
- tests/integration/components/o-s-s/modal-dialog-test.ts
Add illustration named block to OSS::ModalDialog component
> Add illustration named block to OSS::ModalDialog component

- addon/components/o-s-s/content-panel.hbs
- addon/components/o-s-s/content-panel.stories.js
- addon/components/o-s-s/content-panel.ts
- app/components/o-s-s/content-panel.js
- app/styles/organisms/content-panel.less
- app/styles/oss-components.less
- tests/dummy/app/templates/application.hbs
- tests/integration/components/o-s-s/content-panel-test.ts
Add a new dummy component OSS::ContentPanel which has predefined borders & padding that will display the yielded content.
Related to: [#ENG-268](https://linear.app/upfluence/issue/ENG-268/[groundwork]-new-osscontentpanel-component)
> Added new component ContentPanel

- addon/components/o-s-s/text-area.hbs
- addon/components/o-s-s/text-area.stories.js
- addon/components/o-s-s/text-area.ts
- app/components/o-s-s/text-area.js
- app/styles/atoms/input-container.less
- app/styles/molecules/textarea.less
- app/styles/oss-components.less
- tests/dummy/app/templates/application.hbs
- tests/integration/components/o-s-s/text-area-test.ts
Related to: [ENG-269](https://linear.app/upfluence/issue/ENG-269/[groundwork]-new-osstextarea-component)
> New component textArea

- addon/components/o-s-s/password-input.stories.js
- addon/components/o-s-s/password-input.ts
Change default placeholder value for `OSS::PasswordInput`.
Related to: nothing (design update)
> Change default placeholder value for OSS::PasswordInput 

- addon/components/o-s-s/layout/sidebar.hbs
- addon/components/o-s-s/layout/sidebar/item.hbs
- addon/components/o-s-s/layout/sidebar/item.stories.js
- addon/components/o-s-s/layout/sidebar/item.ts
- tests/dummy/app/templates/application.hbs
- tests/integration/components/o-s-s/layout/sidebar/item-test.ts
Handle different action when item is locked or not 
Related to: [#ENG-442](https://linear.app/upfluence/issue/ENG-442/implement-osslayoutssidebar-component)
> Add: defaultAction & lockedAction in sidebar item

- addon/components/o-s-s/icon.hbs
- addon/components/o-s-s/icon.stories.js
- addon/components/o-s-s/icon.ts
- app/components/o-s-s/icon.js
- tests/dummy/app/templates/application.hbs
- tests/integration/components/o-s-s/icon-test.ts
Add OSS:Icon & tests
Related to: https://linear.app/upfluence/issue/ENG-508/ossicon-component
> Add OSS:Icon & tests

- addon/components/o-s-s/text-area.hbs
- tests/integration/components/o-s-s/text-area-test.ts
OSS::TextArea onChange method update from "change' to "keyup"
Related to: https://linear.app/upfluence/issue/ENG-486/[acquisition-web]-builder-page-update
> OSS::TextArea onChange method update

- addon/components/o-s-s/number-input.hbs
- addon/components/o-s-s/number-input.stories.js
- addon/components/o-s-s/number-input.ts
- tests/dummy/app/templates/application.hbs
- tests/integration/components/o-s-s/number-input-test.ts
Add minReachedTooltip and maxReachedTooltip args 
Disable buttons for min max  
Related to: https://linear.app/upfluence/issue/ENG-636/[seats-management]-add-support-for-billingseatsmanagermodal-component
> Add minReachedTooltip and maxReachedTooltip for number-input

- addon/components/o-s-s/email-input.stories.js
- addon/components/o-s-s/email-input.ts
- tests/dummy/app/controllers/application.js
- tests/dummy/app/templates/application.hbs
- tests/integration/components/o-s-s/email-input-test.ts
Add `onChange` method for email-input components
Related to: https://linear.app/upfluence/issue/ENG-781/error-message-not-very-clear-when-trying-to-register-account-with
> Add onChange method for email-input components

- addon/components/o-s-s/tag.stories.js
- addon/components/o-s-s/tag.ts
- app/styles/base/_tags.less
- app/styles/core-v2/_colors.less
Add support for ChatGPT tag skin.
> Add support for ChatGPT tag skin.

- addon/modifiers/enable-tooltip.ts
enable-tooltip: destroy on click when only triggered on hover
> enable-tooltip: destroy on click when only triggered on hover

- addon/components/o-s-s/array-input.stories.js
- addon/components/o-s-s/attributes-panel.hbs
- addon/components/o-s-s/attributes-panel.stories.js
- addon/components/o-s-s/attributes-panel.ts
- app/components/o-s-s/attributes-panel.js
- app/styles/organisms/attributes-panel.less
- app/styles/oss-components.less
- tests/dummy/app/controllers/application.js
- tests/dummy/app/templates/application.hbs
- tests/integration/components/o-s-s/attributes-panel-test.ts
- tests/integration/components/o-s-s/infinite-select-test.js
- translations/en-us.yaml
Add new OSS::AttributesPanel component
Add tests & documentation
Related to: https://linear.app/upfluence/issue/ENG-1555/[oss-components]-new-ossattributespanel-component
> New OSS::AttributesPanel component

- addon/components/o-s-s/attribute/country.ts
- addon/components/o-s-s/attribute/text.hbs
- addon/components/o-s-s/attribute/text.stories.js
- addon/components/o-s-s/attribute/text.ts
- app/components/o-s-s/attribute/text.js
- tests/integration/components/o-s-s/attribute/text-test.ts
OSS::Attribute::Text update:
- move the file according to his name
- before hovering the inline copy should be NOT visible
- default value for `copyable` arg set to true
- tests
Related to: https://linear.app/upfluence/issue/ENG-1564/[ember-influencer]-new-attributespanelshippingaddress-component-and
> OSS::Attribute::Text update

- addon/components/o-s-s/attributes-panel.hbs
- addon/components/o-s-s/attributes-panel.stories.js
- addon/components/o-s-s/attributes-panel.ts
- tests/integration/components/o-s-s/attributes-panel-test.ts
Disabled the save button in edition mode for attributes-panel
Related to: https://linear.app/upfluence/issue/ENG-1753/save-button-is-enabled-when-shipping-address-section-is-empty
> Disabled the save button in edition mode for attributes-panel

- addon/components/o-s-s/attribute/base.hbs
- addon/components/o-s-s/attribute/base.ts
- addon/components/o-s-s/attribute/country.hbs
- addon/components/o-s-s/attribute/text.hbs
- addon/components/o-s-s/attribute/text.ts
- app/components/o-s-s/attribute/base.js
- tests/dummy/app/templates/application.hbs
- tests/integration/components/o-s-s/attribute/base-test.ts
- tests/integration/components/o-s-s/attribute/text-test.ts
Adds Attribute::Base component with tests
Linked to: https://linear.app/upfluence/issue/ENG-1559/[oss-components]-new-ossattributerevealemail-component
> Adds Attribute::Base component with tests

- app/styles/atoms/input-container.less
- tests/dummy/app/templates/application.hbs
Updated padding for prefix & suffix of OSS::InputContainer.
Also updated the clickable area of the suffix.
> Updated: inputContainer's prefix & suffix padding and suffix hitbox

- addon/components/o-s-s/attribute/phone-number.hbs
- addon/components/o-s-s/attribute/phone-number.stories.js
- addon/components/o-s-s/attribute/phone-number.ts
- app/components/o-s-s/attribute/phone-number.js
- tests/dummy/app/templates/application.hbs
- tests/integration/components/o-s-s/attribute/phone-number-test.ts
- translations/en-us.yaml
Adds OSS::Attribute::PhoneNumber along with documentation and tests
> Adds OSS::Attribute::PhoneNumber along with documentation and tests

- addon/components/o-s-s/attribute/removable-text.hbs
- addon/components/o-s-s/attribute/removable-text.stories.js
- addon/components/o-s-s/attribute/removable-text.ts
- addon/components/o-s-s/attribute/tag-array.hbs
- addon/components/o-s-s/attribute/tag-array.stories.js
- addon/components/o-s-s/attribute/tag-array.ts
- app/components/o-s-s/attribute/removable-text.js
- app/components/o-s-s/attribute/tag-array.js
- app/components/o-s-s/attribute/tagada.js
- app/styles/atoms/attribute.less
- tests/dummy/app/controllers/application.js
- tests/dummy/app/templates/application.hbs
- tests/integration/components/o-s-s/attribute/removable-text-test.ts
- tests/integration/components/o-s-s/attribute/tag-array-test.ts
- translations/en-us.yaml
Adds OSS::Attribute::TagArray component along with tests and documentation
> Adds OSS::Attribute::TagArray component along with tests and documentation

- addon/components/o-s-s/country-selector.ts
- tests/dummy/app/controllers/application.js
- tests/dummy/app/templates/application.hbs
- tests/integration/components/o-s-s/country-selector-test.ts
Adds the ability to specify country-selector province mode with code value
> Adds the ability to specify country-selector province mode with code value

- index.js
- package.json
- yarn.lock
Bump @fortawesome/fontawesome-pro to ^6.4.2 and remove fallback on free version
Related to: https://linear.app/upfluence/issue/ENG-1760/upgrade-to-font-awesome-6
> Bump @fortawesome/fontawesome-pro to ^6.4.2

- .prettierrc.js
- addon/components/o-s-s/currency-input.hbs
- addon/components/o-s-s/currency-input.stories.js
- addon/components/o-s-s/currency-input.ts
- tests/dummy/app/controllers/application.js
- tests/dummy/app/templates/application.hbs
- tests/integration/components/o-s-s/currency-input-test.ts
Adds a @allowedCurrencies parameter to `OSS::CurrencyInput` which allows to pass a custom set of currencies that will be displayed in the dropdown.
Also cleans up the typescript code & updates tests.
> Added: option to pass custom data set to currency input + cleanup

- addon/components/o-s-s/attribute/base.hbs
- addon/components/o-s-s/skeleton.ts
- addon/components/o-s-s/social-post-badge.stories.js
- addon/components/o-s-s/toggle-buttons.hbs
- addon/components/o-s-s/toggle-buttons.stories.js
- addon/components/o-s-s/toggle-buttons.ts
- app/styles/atoms/attribute.less
- tests/integration/components/o-s-s/attribute/text-test.ts
- tests/integration/components/o-s-s/toggle-buttons-test.ts
Allow null value for `selectedToggle` in OSS::Toggle-buttons
Add animation for copy icon in `attribute/base` component
Related to: https://linear.app/upfluence/issue/ENG-1566/[ember-influencer]-new-attributespanelcreatorinformation-component-and
> Allow null value for selectedToggle in OSS::Toggle-buttons

- addon/components/o-s-s/banner.hbs
- addon/components/o-s-s/banner.stories.js
- tests/integration/components/o-s-s/banner-test.ts
Because sometimes we need a bit more complex things in the banner's titlte (like a powered by X logo)
> OSS::Banner: add support for title named-block

- app/styles/base/_stats.less
- app/templates/components/upf-stat.hbs
It fixes the display of upf stat label
Related to: #
https://linear.app/upfluence/issue/ENG-2079/creator-media-stats-have-bad-alignment-in-sidepanel
Fixes display issues that emerged with [this commit](https://github.com/upfluence/oss-components/commit/18b0769fc88941eb1cfa285592ecc07457f90689). A condition is added in order to switch classes when a tooltip is present.
> Fixed upf-stat__label issue

- index.js
- package.json
Resolve deps differently depending on whether the parent is an addon or an app (inspired by EBM)
> Resolve deps differently depending on whether the parent is an addon or an app (inspired by EBM)

- addon/components/o-s-s/attribute/removable-text.ts
- addon/components/o-s-s/attribute/revealable-email.ts
- addon/components/o-s-s/phone-number-input.ts
- addon/components/o-s-s/select.ts
- addon/components/o-s-s/upload-area.ts
- addon/components/o-s-s/url-input.ts
- package.json
- pnpm-lock.yaml
- tests/dummy/app/routes/application.js
- tests/integration/components/o-s-s/access-panel-test.ts
- tests/integration/components/o-s-s/attribute/base-test.ts
- tests/integration/components/o-s-s/attribute/country-test.ts
- tests/integration/components/o-s-s/attribute/phone-number-test.ts
- tests/integration/components/o-s-s/attribute/removable-text-test.ts
- tests/integration/components/o-s-s/attribute/revealable-email-test.ts
- tests/integration/components/o-s-s/attribute/text-test.ts
- tests/integration/components/o-s-s/attributes-panel-test.ts
- tests/integration/components/o-s-s/badge-test.ts
- tests/integration/components/o-s-s/code-block-test.ts
- tests/integration/components/o-s-s/copy-test.ts
- tests/integration/components/o-s-s/country-selector-test.ts
- tests/integration/components/o-s-s/currency-input-test.ts
- tests/integration/components/o-s-s/infinite-select-test.js
- tests/integration/components/o-s-s/power-select-test.ts
- tests/integration/components/o-s-s/select-test.ts
- tests/integration/components/o-s-s/upload-item-test.ts
- tests/integration/components/o-s-s/url-input-test.ts
Related to: #[VEL-2179](https://linear.app/upfluence/issue/VEL-2179/upgrade-ember-intl-to-v6)
> Ember-intl: Migrate to v6.4

- addon/components/o-s-s/togglable-section.hbs
- addon/components/o-s-s/togglable-section.stories.js
- addon/components/o-s-s/togglable-section.ts
- app/styles/molecules/togglable-section.less
- tests/dummy/app/templates/application.hbs
- tests/integration/components/o-s-s/togglable-section-test.ts
Fixes layout padding & alignment, see videos :
broken/old design:
https://github.com/upfluence/oss-components/assets/5032005/0db90846-c12b-422b-9fdf-9b67d72b03ef
Fixed version:
https://github.com/upfluence/oss-components/assets/5032005/1652c458-5297-48e9-870d-ed06d0461871
In the software the changes will be from (ugly) :
to (nice):
Also added the option to pass a default badgeIcon directly.
> Fixed: OSS::TogglableSection padding & alignment + option to pass a badge

- addon/components/o-s-s/togglable-section.hbs
- addon/components/o-s-s/togglable-section.stories.js
- addon/components/o-s-s/togglable-section.ts
- app/styles/molecules/togglable-section.less
- tests/dummy/app/templates/application.hbs
- tests/integration/components/o-s-s/togglable-section-test.ts
TogglableSection is not dependent on OSS::Banner anymore.
Added two new arguments:
- Disabled (sets the switch state to disabled when truthy)
- size (`sm` or `md` defaults to `md`)
> Added: TogglableSection small rework plus added options

- addon/components/o-s-s/chip.hbs
- addon/components/o-s-s/chip.stories.js
- app/styles/atoms/chip.less
- tests/integration/components/o-s-s/chip-test.ts
oss/chip: add support for prefix named block
> oss/chip: add support for prefix named block

- addon/components/o-s-s/avatar-group.hbs
- addon/components/o-s-s/avatar-group.stories.js
- addon/components/o-s-s/avatar-group.ts
- addon/components/o-s-s/avatar.hbs
- addon/components/o-s-s/avatar.stories.js
- addon/components/o-s-s/avatar.ts
- app/components/o-s-s/avatar-group.js
- app/styles/atoms/avatar.less
- app/styles/molecules/avatar-group.less
- app/styles/oss-components.less
- tests/integration/components/o-s-s/avatar-group-test.ts
- tests/integration/components/o-s-s/avatar-test.ts
- Add support for OSS::AvatarGroup component
- Add support for loading/placeholder states on OSS::Avatar
> Add support for OSS::AvatarGroup component

- addon/components/o-s-s/power-select.hbs
- addon/components/o-s-s/power-select.stories.js
- addon/components/o-s-s/power-select.ts
- addon/components/o-s-s/private/base-dropdown.ts
- addon/components/o-s-s/select.hbs
- addon/components/o-s-s/select.stories.js
- addon/components/o-s-s/select.ts
- addon/utils/attach-dropdown.ts
- app/styles/base/_infinite-select.less
- app/styles/molecules/select.less
- app/styles/power-select.less
- tests/integration/components/o-s-s/power-select-test.ts
- tests/integration/components/o-s-s/select-test.ts
This reverts commit fe847cd33f2f4c367cbeecfc6cbb20cfbc995f31, reversing changes made to 7ccf9e6ef54241ea4c69cc87e1aaea10ebeff3b6.
Reintroduce `OSS::Select` & `OSS::PowerSelect` updates w/ portaled-dropdowns and:
- automatic positioning
- exclusive dropdowns (prevent having two dropdowns displayed at once — this only concerns those extending the `BaseDropdown` class) 
- CSS-targetable dropdowns via the `addressableAs` arg (to style them easily despite them being renderered in a portal) 
Compared to the initial implementation, I finally ended up letting the `div` elements instead of using `details/summary`. However, I decided to replicate the `open` attribute that came in handy and is added on the component when the dropdown is being displayed.
To keep them in sync and update the `isOpen` …
> [VEL-2833] Reintroduce portal-based select updates

- app/styles/atoms/button.less
Add disabled class for square button. The disabled doesn't exist when we add the `@square={{true}}` to `OSS::Button`
> Add disabled class for square button

- addon/components/o-s-s/modal-dialog.stories.js
- addon/components/o-s-s/modal-dialog.ts
- addon/components/o-s-s/private/base-modal.ts
- addon/components/o-s-s/split-modal.stories.js
- addon/components/o-s-s/split-modal.ts
- tests/dummy/app/templates/application.hbs
- tests/integration/components/o-s-s/modal-dialog-test.ts
- tests/integration/components/o-s-s/split-modal-test.ts
Related to: #[DRA-651](https://linear.app/upfluence/issue/DRA-651/prevent-click-from-closing-some-modals-if-an-action-was-performed)
New optional params `disableClickOutside`
> Modal dialog: Add params to disable clickOutside

- app/styles/molecules/togglable-section.less
Fixed: OSS::TogglableSection rounded corners without overflow hidden
> Fixed: OSS::TogglableSection rounded corners without overflow hidden

- addon/components/o-s-s/input-container.hbs
- addon/components/o-s-s/input-container.stories.js
- addon/components/o-s-s/input-container.ts
- tests/integration/components/o-s-s/input-container-test.js
Updated: OSS::InputContainer with new hasError param + updated tests
> Updated: OSS::InputContainer with new hasError param + updated tests

- addon/components/o-s-s/currency-input.hbs
- addon/components/o-s-s/currency-input.stories.js
- addon/components/o-s-s/currency-input.ts
- app/styles/currency-input.less
- tests/dummy/app/templates/application.hbs
- tests/integration/components/o-s-s/currency-input-test.ts
Add disabled state for currency-input component
> Add disabled state for currency-input component

- addon/components/o-s-s/currency-input.hbs
- tests/integration/components/o-s-s/currency-input-test.ts
Add disabled attribute for currency input
> Add disabled attribute for currency input

- addon/components/o-s-s/progress-bar.stories.js
- addon/components/o-s-s/progress-bar.ts
- app/styles/molecules/progress-bar.less
- tests/dummy/app/templates/application.hbs
- tests/integration/components/o-s-s/progress-bar-test.ts
Adds a new `danger` skin to the component
Adds a new `coloredBackground` argument which displays a lighter colored background based on the selected skin.
> Updated: OSS::ProgressBar new skin and new option for light background

- addon/components/o-s-s/dialog.hbs
- addon/components/o-s-s/dialog.stories.js
- addon/components/o-s-s/dialog.ts
- tests/integration/components/o-s-s/dialog-test.ts
Add error skin for OSS::Dialog
> Add error skin for OSS::Dialog

- addon/components/o-s-s/dialog.hbs
- addon/components/o-s-s/dialog.stories.js
- addon/components/o-s-s/dialog.ts
- tests/dummy/app/templates/application.hbs
- tests/integration/components/o-s-s/dialog-test.ts
Related to: #[DRA-1046](https://linear.app/upfluence/issue/DRA-1046/dialog-box-to-confirm-if-users-wants-to-define-default-account-email)
> OSS-Components - Edited: dialog component to include skin and icon args

- addon/components/o-s-s/copy.hbs
- addon/components/o-s-s/copy.stories.js
- addon/components/o-s-s/copy.ts
- tests/dummy/app/templates/application.hbs
- tests/integration/components/o-s-s/avatar-test.ts
- tests/integration/components/o-s-s/copy-test.ts
> Add icon option for OSS::Copy

- addon/components/o-s-s/dialog.stories.js
- addon/components/o-s-s/dialog.ts
- tests/dummy/app/controllers/application.js
- tests/dummy/app/templates/application.hbs
- translations/en-us.yaml
Added the option to pass a safe string to the title of the OSS::Dialog component.
Necessary for: #[DRA-1046](https://linear.app/upfluence/issue/DRA-1046/dialog-box-to-confirm-if-users-wants-to-define-default-account-email)
> na/DRA-1046 - Added: safe string acceptance on oss-dialog title

- addon/components/o-s-s/popover.hbs
- addon/components/o-s-s/popover.stories.js
- addon/components/o-s-s/popover.ts
- addon/modifiers/attach-element.stories.js
- addon/modifiers/attach-element.ts
- addon/utils/attach-dropdown.ts
- app/components/o-s-s/popover.js
- app/modifiers/attach-element.js
- app/styles/organisms/popover.less
- app/styles/oss-components.less
- tests/integration/components/o-s-s/popover-test.ts
- tests/integration/modifiers/attach-element-test.ts
This PR adds support for an `attach-element` modifier that uses FloatingUI (via the `attachDropdown` util function) to attach a given element to another.
Invoking it looks like:
```handlebars
<div class="reference-element">
I am the reference!
</div>
<div class="attached-element" {{attach-element to=".reference-element"}}>
I am floaaaaaating !
</div>
```
It also promotes the OSS::Popover component from candidate (in ember-influencer) to global implementation.
> Add support for an `attach-element` modifier

- app/styles/molecules/progress-bar.less
the removal of the `forwards` in the animation definition fixes the animation for a multi-step usage.
Normal use case with `forwards`
https://github.com/user-attachments/assets/a5e94f32-0a43-4105-9f57-f9bdd76f047d
Normal use case without it
https://github.com/user-attachments/assets/1011109a-bc0a-4491-8e10-4bd8c730bc90
Mutli-step with `forwards`
https://github.com/user-attachments/assets/a5d8c9ac-f6f6-4594-86dc-5e13fc1b3d81
Multistep without it
https://github.com/user-attachments/assets/620f5a7e-d892-4417-886f-5efae11ec931
> Fixed: Multistep OSS::ProgressBar animation

- app/styles/base/_tags.less
- tests/dummy/app/templates/index.hbs
This PR adds a plain mode to the chat-gpt skin for the OSS::Tag component
> Add plain to chat-gpt tag skin

- app/styles/base/_slider.less
This PR removes the default spinner buttons on the slider in Firefox
> Column filter input field issue on Firefox

- addon/components/o-s-s/scrollable-panel.hbs
- addon/components/o-s-s/scrollable-panel.stories.js
- addon/components/o-s-s/scrollable-panel.ts
- app/styles/organisms/scrollable-panel.less
Added "plain" optional argument on OSS::ScrollablePanel to allow for choosing between grey or white shadows.
Related to: #[DRA-1560](https://linear.app/upfluence/issue/DRA-1560/[identity-web]-user-roles-and-permissions-make-the-user-management)
> Added: plain option for scrollable panel component

- addon/components/o-s-s/carousel.hbs
- addon/components/o-s-s/carousel.stories.js
- addon/components/o-s-s/carousel.ts
- app/components/o-s-s/carousel.js
- app/styles/organisms/carousel.less
- app/styles/oss-components.less
- tests/dummy/app/templates/index.hbs
- tests/integration/components/o-s-s/carousel-test.ts
New OSS::Carousel component
```
interface OSSCarouselArgs {
buttonIcon?: string;
animationStyle?: 'shift' | 'slide';
showIndicators?: boolean;
showControls?: 'overlay' | 'outside';
autoPlay?: number;
}
```
Usage:
```handlebars
<OSS::Carousel @showIndicators={{this.showIndicators}} @showControls={{this.showControls}}
@animationStyle={{this.animationStyle}} @buttonIcon={{this.buttonIcon}}
@autoPlay={{this.autoPlay}}>
<:pages>
<div class="page">
<OSS::Banner @icon="fas fa-image" @title="PAGE 1"/>
</div>
<div class="page">
<OSS::Banner @icon="fas fa-image" @title="PAGE 2"/>
</div>
<div class="page">
<OSS::Banner @icon="fas fa-image" @title="PAGE 1"/>
</div>
</:pages>
</OSS::Carousel>
```
With controls, `outside`:
With controls, `overlay` (would be more useful with pictures for example): …
> New OSS::Carousel component

- app/styles/base/_inputs.less
- app/templates/components/input-wrapper.hbs
Removes the `col-xs` bootstrap class from the soon to be deprecated `InputWrapper` component
> Removed: bootstrap's col-xs usage from InputWrapper

- addon/components/o-s-s/toggle-buttons.ts
Remove event.stopPropagation in select toggle for OSS::ToggleButtons. I check in all OSS::ToggleButtons, it is not intriduce any issue. In some cases, this leads to UX inconsistencies on dropdown closures.
> Remove event.stopPropagation in select toggle for OSS::ToggleButtons

- addon/components/o-s-s/button.hbs
- addon/components/o-s-s/button.stories.js
- addon/components/o-s-s/button.ts
- tests/integration/components/o-s-s/button-test.ts
This PR introduces a `loadingOptions` optional arg on the `OSS::Button` component to allow us to fine tune it. This is because we now have a case where we want to display the button's label even when loading.
> OSS::Button: Add support for `@loadingOptions` arg

- addon/components/o-s-s/information-section.hbs
- addon/components/o-s-s/information-section.stories.js
- addon/components/o-s-s/information-section.ts
- app/components/o-s-s/information-section.js
- app/styles/atoms/information-section.less
- app/styles/core/_colors.less
- app/styles/oss-components.less
- tests/integration/components/o-s-s/information-section-test.ts
It adds a new component used in the 2FA project
Related to: #
> OSS::InformationSection component

- app/styles/shims/bootstrap.less
Remove Bootstrap imports we are sure we are not using across the apps. This needs to be merged after: https://github.com/upfluence/uedit/pull/76.
> Remove Bootstrap imports we are sure we are not using across the apps

- addon/components/o-s-s/information-section.hbs
- addon/components/o-s-s/information-section.stories.js
- addon/components/o-s-s/information-section.ts
- app/components/o-s-s/information-section.js
- app/styles/atoms/information-section.less
- app/styles/core/_colors.less
- app/styles/oss-components.less
- tests/integration/components/o-s-s/information-section-test.ts
It adds a new component used in the 2FA project
Related to: #
> OSS::InformationSection component from 2FA branch

- linters/handlebars/index.js
This PR updates the internal handlebars linter w/ all rules that are turned-off as we start properly linting our templates. The idea is to gradually enable again the turned-off rules and add custom ones in the future.
> Define all @upfluence template linting rules in our plugin to be extended by others

- addon/components/o-s-s/upload-area.stories.js
- addon/components/o-s-s/upload-area.ts
- tests/integration/components/o-s-s/upload-area-test.ts
OSS::UploadArea: add support `onDryRun` allowing the parent to stop after the file validation and get the File to deal w/ it.
> [VEL-3663] OSS::UploadArea: add support onDryRun action support

- .storybook/main.js
- addon-test-support/index.ts
- addon-test-support/setup-toast.ts
- addon-test-support/test-helpers.stories.mdx
- addon/components/o-s-s/dialog.hbs
- addon/components/o-s-s/dialog.stories.js
- addon/components/o-s-s/dialog.ts
- tests/integration/components/o-s-s/code-block-test.ts
- tests/integration/components/o-s-s/copy-test.ts
- tests/integration/components/o-s-s/dialog-test.ts
- tests/integration/components/o-s-s/upload-area-test.ts
- OSS::Dialog: add support for icons on the action buttons
- Add a `setupToast` test util fn for setting up toast stubbing
> OSS::Dialog: add support for icons on the action buttons

- addon/components/o-s-s/mode-switch.hbs
- addon/components/o-s-s/mode-switch.stories.js
- addon/components/o-s-s/mode-switch.ts
- app/components/o-s-s/mode-switch.js
- app/styles/mode-switch.less
- app/styles/oss-components.less
- tests/dummy/app/controllers/visual.ts
- tests/dummy/app/templates/visual.hbs
- tests/integration/components/o-s-s/mode-switch-test.ts
This PR move the BehaviourSwitch from Facade-Web to OSSComponents, renaming it ModeSwitch
Related to: #
> Added ModeSwitch component to OSS

- addon/components/o-s-s/empty-state.hbs
- addon/components/o-s-s/empty-state.stories.js
- addon/components/o-s-s/empty-state.ts
- app/components/o-s-s/empty-state.js
- tests/dummy/app/templates/index.hbs
- tests/integration/components/o-s-s/empty-state-test.ts
This PR adds an empty state component
> Empty state component

- addon/components/o-s-s/currency-input.ts
- addon/components/o-s-s/phone-number-input.hbs
- addon/components/o-s-s/phone-number-input.ts
- tests/integration/components/o-s-s/phone-number-input-test.ts
OSS::PhoneNumberInput component updated to properly handle paste events.
On paste, from keyboard shortcuts or click action (right click + paste) the cliboard data is parsed to keep only numeric characters.
> Updated: PhoneNumberInput component now handles paste events

- addon/components/o-s-s/power-select.hbs
- addon/components/o-s-s/power-select.stories.js
- addon/components/o-s-s/power-select.ts
- app/styles/power-select.less
- tests/integration/components/o-s-s/power-select-test.ts
> Added borderless attr for power select

- addon/components/o-s-s/togglable-section.hbs
- addon/components/o-s-s/togglable-section.stories.js
- tests/dummy/app/templates/index.hbs
- tests/integration/components/o-s-s/togglable-section-test.ts
Related to: #[DRA-2652](https://linear.app/upfluence/issue/DRA-2652/[publishr-admin-web]-add-application-received-tag-to-marketplace)
Adding an `actions` named block to the `<OSS::TogglableSection/>` component. 
This name block should allow us to overwrite the component behavior by adding content directly in the header of the `TogglableSection` between the title & the toggle when needed
> Togglable section: Add new actions named block

- addon/components/o-s-s/input-container.ts
- tests/integration/components/o-s-s/input-container-test.js
Currently `stopImmediatePropagation` & `preventDefault` are blocking paste event overwritten by other inputs.
The goal of this pr is to retreive the normal behavior on other inputs
Related to: #[VEL-5446](https://linear.app/upfluence/issue/VEL-5446/we-cant-paste-values-into-some-inputs-in-the-platform)
> Input container: Remove stopImmediatePropagation/preventDefault from paste event

- addon/components/o-s-s/access-panel.hbs
- addon/components/o-s-s/access-panel.ts
- tests/integration/components/o-s-s/access-panel-test.ts
Make the onSearch argument of the OSS::AccessPanel optional
> Make the onSearch argument of the OSS::AccessPanel optional

- addon/utils/attach-dropdown.ts
Add fallbackPlacements option to attach-dropdown
> Add fallbackPlacements option to attach-dropdown

- addon/components/o-s-s/infinite-select.hbs
- addon/components/o-s-s/infinite-select.ts
Fix input focus changing when hovering a dropdown item
Related to: #
https://github.com/user-attachments/assets/3eaffb24-697d-417a-b3bc-7f76facaae4d
> Fix input focus

- addon/components/o-s-s/country-selector.hbs
- addon/components/o-s-s/country-selector.ts
- addon/components/o-s-s/phone-number-input.hbs
- addon/components/o-s-s/phone-number-input.ts
- addon/components/o-s-s/private/base-dropdown.ts
Use portaled select dropdowns for both OSS::CountrySelector & OSS::PhoneNumberInput in order to properly:
- escape overflow hidden traps
- have autoplacement
> Use portaled dropdowns for OSS::CountrySelector & OSS::PhoneNumberInput

- addon/components/o-s-s/checkbox.stories.js
- addon/components/o-s-s/checkbox.ts
- addon/components/o-s-s/power-select.hbs
- addon/components/o-s-s/power-select.stories.js
- addon/components/o-s-s/power-select.ts
- addon/components/o-s-s/private/base-dropdown.ts
- addon/components/o-s-s/select.ts
- app/styles/array-input.less
- app/styles/base/_checkboxes.less
- app/styles/molecules/select.less
- app/styles/power-select.less
- app/styles/utilities/_borders.less
- tests/dummy/app/controllers/input.ts
- tests/dummy/app/templates/input.hbs
- tests/dummy/app/templates/visual.hbs
- tests/integration/components/o-s-s/checkbox-test.ts
- tests/integration/components/o-s-s/power-select-test.ts
This follows the same implementation & usage as we have for our `OSS::InputContainer` component
Before update:
After update:
Required test files & storybook entries have been updated.
Linked to:
- https://linear.app/upfluence/issue/DRA-2868/oss-components-osscheckbox-error-state-osspowerselect-errormessage
- https://linear.app/upfluence/issue/DRA-2721/improve-ossselect-component-persistent-search-input
> OSS::Checkbox, OSS::PowerSelect, OSS::Select Updates

- addon/services/form-manager.ts
- tests/unit/services/form-manager-test.ts
It adds a new `setFieldFeeback` message to the FormManager service.
This method is also returned as a FormInstance which allows easy usage from a parent caller.
e.g. On an error received from the API
```typescript
private errorHandler({ errors }: { errors: RoleError[] }): void {
this.args.role.rollbackAttributes();
if (errors?.[0]?.detail) {
const { resource, field, code } = errors[0]?.detail;
if (resource === 'role' && field === 'name' && code === 'taken') {
this.formInstance.setFieldFeedback('roleName', {
kind: 'error',
message: {
type: 'error',
value: this.intl.t('roles.error.name.already_exist')
}
});
}
return this.toast.error(this.intl.t('roles.error.name.already_exist'), this.intl.t('roles.update.error.title'));
}
this.toast.error(this.intl.t('roles.update.error.subtitle'), …
```
> Updated: FormManager service with setFieldFeedback method

- app/styles/molecules/select.less
Fixed: OSS::Select display overflow when search is disabled
both version are now displaying properly:
> Fixed: OSS::Select display overflow when search is disabled

- addon/components/o-s-s/country-selector.ts
- tests/integration/components/o-s-s/avatar-test.ts
The current implementation of the OSS::CountrySelector focuses the input selector when the component is instanciated with an existing value.
This PR disables this, only when instanciating with a valid argument, as it messes up focusing rules in some other components.
Making a selection and then closing the dropdown still focuses the input selector as it did before.
> Updated: prevent autofocus of CountrySelector on load

- addon/components/o-s-s/scrollable-panel.hbs
- addon/components/o-s-s/scrollable-panel.stories.js
- addon/components/o-s-s/scrollable-panel.ts
- app/styles/organisms/scrollable-panel.less
- tests/integration/components/o-s-s/scrollable-panel-test.ts
Related to: #
Add a new optional `onBottomReached` action wich is triggered when the user scroll to the bottom of the scrollable panel.
Furthermore added few micro-improvement on the component himself:
- ResizeObserver => showing/hidding shadows, when the content size of the scroll has changed
- CSS update => Automatically handle shadow when parent has a max-size defined
> Scrollable-panel: Add new onBottomReached action & micro-improvement on content resize

- addon/components/o-s-s/badge.ts
- addon/components/o-s-s/expandable-badge.hbs
- addon/components/o-s-s/expandable-badge.stories.js
- addon/components/o-s-s/expandable-badge.ts
- addon/components/o-s-s/stack-container.hbs
- addon/components/o-s-s/stack-container.stories.js
- addon/components/o-s-s/stack-container.ts
- app/components/o-s-s/expandable-badge.js
- app/components/o-s-s/stack-container.js
- app/styles/atoms/expandable-badge.less
- app/styles/molecules/stack-container.less
- app/styles/oss-components.less
- tests/dummy/app/templates/visual.hbs
- tests/integration/components/o-s-s/expandable-badge-test.ts
- tests/integration/components/o-s-s/stack-container-test.ts
Introduces two new components.
A new badge component that expands to show a label.
https://github.com/user-attachments/assets/2e0f3b01-9ccb-454c-adee-3ff476c3541e
Note:
The behaviour on desktop is to expand on hover while it is on "tap" events for mobile.
It extends the existing OSS::Badge so that all its features & parameters remain functional.
On top of that, it adds the following parameters:
- expandedLabel: the label displayed on hover / touch
- flag: allows rendering an fflag as icon inside the badge
- fontColorClass: allows passing a class that will be applied to the icon & label
---
https://github.com/user-attachments/assets/da4ec940-3f9f-4ae4-b1d5-d6114dea5f0c
A new component that allows us to have row & column stacks with negative margins.
It has the following options:
- …
> OSS::ExpandableBadge & OSS::StackContainer

- addon/components/o-s-s/expandable-badge.hbs
- addon/components/o-s-s/expandable-badge.stories.js
- addon/components/o-s-s/expandable-badge.ts
- tests/integration/components/o-s-s/expandable-badge-test.ts
Separates arguments for setting custom classes on the badge icon and on the badge label.
Updated tests & documentation.
> OSS::ExpandableBadge - new argument for custom span class

- app/styles/core/_all.less
- app/styles/core/_form.less
- app/styles/core/_form.stories.mdx
Add oss-label class, in a new `_form.less` stylesheet, aiming to improve consistency within the forms. 
Related to: #
> Add oss-label class

- addon/components/o-s-s/input-container.hbs
- addon/components/o-s-s/input-container.stories.js
- addon/components/o-s-s/input-container.ts
- addon/components/o-s-s/input-group.hbs
- addon/components/o-s-s/input-group.stories.js
- addon/components/o-s-s/input-group.ts
- addon/components/o-s-s/slider.hbs
- addon/components/o-s-s/slider.stories.js
- addon/components/o-s-s/slider.ts
- tests/dummy/app/templates/input.hbs
- tests/integration/components/o-s-s/input-container-test.js
- tests/integration/components/o-s-s/input-group-test.ts
- tests/integration/components/o-s-s/slider-test.ts
Add autocomplete option to OSS::Slider, which is activated by default.
The Input element has a native autocomplete arg which takes only "on" or "off" values. More information in this documentation: https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Attributes/autocomplete#off
Since the autocomplete option was needed in the OSS::Slider, the arg had to be propagated in the OSS::InputGroup used in the Slider as well as in the OSS::InputContainer used in the OSS::InputGroup.
Tests and stories have been updated to manage and showcase this new option.
Related to: #
> Add autocomplete arg to slider

- addon/components/o-s-s/badge.ts
- addon/components/o-s-s/completion-badge.hbs
- addon/components/o-s-s/completion-badge.stories.js
- addon/components/o-s-s/completion-badge.ts
- addon/components/o-s-s/expandable-badge.ts
- app/components/o-s-s/completion-badge.js
- app/styles/atoms/completion-badge.less
- app/styles/oss-components.less
- tests/dummy/app/controllers/visual.ts
- tests/dummy/app/templates/visual.hbs
- tests/integration/components/o-s-s/badge-test.ts
- tests/integration/components/o-s-s/completion-badge-test.ts
_**YABC**_ - _Yet another badge component_
The CompletionBadge component brings a new badge component with a custom progression border around it.
It extends `OSS::Badge` and thus features the same options, such as size, skin, plain, etc. (Minor updates were made to the Badge component class to have better TS typings)
The progression value can be passed as a value between 0 & 100 in the `@progress` variable; this value will then be used to apply the correct border around the component.
Not providing a value defaults to 0, and going above 100 will cap the progress at 100.
https://github.com/user-attachments/assets/9e37b3f5-b20b-4290-a37a-cf6f2c9c5935
As you can see in the video, it also supports the ability to react to the live updates of the `progress` value.
There's a code example of this …
> OSS::CompletionBadge

- addon/components/o-s-s/layout/sidebar/item.hbs
- addon/components/o-s-s/layout/sidebar/item.stories.js
- addon/components/o-s-s/layout/sidebar/item.ts
- app/styles/organisms/sidebar.less
- tests/dummy/app/templates/application.hbs
- tests/integration/components/o-s-s/layout/sidebar/item-test.ts
Add tag option for OSS::SIdebar::Item & tests
> Add tag option for OSS::SIdebar::Item & tests

- addon/helpers/format-money.ts
- tests/integration/helpers/format-money-test.ts
Remove compact notion for value inferior to 1000 to avoid displaying unnecessary rounding. This allows alignment with the existing `format-numeric` helper
Before the fix with compact true:
- 859.89 -> 860
- 1256.56 -> 1.2k
After the fix with compact true:
- 859.89 -> 859.89
- 1256.56 -> 1.2k
> Remove compact notion for value inferior to 1000

- addon/components/o-s-s/layout/sidebar/group.hbs
- addon/components/o-s-s/layout/sidebar/group.ts
- addon/components/o-s-s/layout/sidebar/item.hbs
- addon/components/o-s-s/layout/sidebar/item.ts
- app/styles/organisms/sidebar.less
Visual (logo size / active color) & group delay fixes:
- Upfluence logo is moving a bit when hovering it when workflow app is selected
- Improve group menu reactivity when collapsed
- There are weird color changes gray/blue when selecting an app. It doesn't seem consistent depending on if the app is in a group or not. This is also the case when the sidebar is collapsed with icon colors (come from the focus style)
> Visual (logo size / active color) & group delay fixes

- addon/components/o-s-s/currency-input.hbs
- addon/components/o-s-s/phone-number-input.hbs
- tests/integration/components/o-s-s/currency-input-test.ts
- tests/integration/components/o-s-s/phone-number-input-test.ts
Auto focus search inputs in currency-input and phone-number inputs' dropdown
Related to: #
> Focus search inputs in currency and phone-number inputs

- addon/components/o-s-s/smart/immersive/input.hbs
- addon/components/o-s-s/smart/immersive/input.stories.js
- app/styles/atoms/smart/immersive-input.less
- tests/dummy/app/templates/smart.hbs
- tests/integration/components/o-s-s/smart/immersive/input-test.ts
Related to: #[DRA-3557](https://linear.app/upfluence/issue/DRA-3557/publishr-admin-web-new-affiliatecommission-step)
Allow prefix/suffix name block on OSS::Smart::Immersive::Input component
> Smart immersive input: Handle suffix/prefix name block
